from django.urls import path # type: ignore
from . import views

urlpatterns = [
    ##---MAIN DASHBOARDS----
    path("obs-dashboard/", views.IncompleteForms, name="IncompleteForms"),
    path("sup-dashboard/", views.sup_dashboard_view, name='sup_dashboard'),
    path("client-dashboard", views.client_dashboard_view, name="c_dashboard"),
    path("adminDash/<str:selector>", views.adminDash, name="adminDash"),
    
    path("<str:facility>/default-dashboard", views.default_dashboard, name="defaultDash"),
    
    ##---ADMIN PAGES -------
    path("admin-pages/addFAQ", views.admin_add_FAQ_view, name="adminFAQ"),
    path('api/get_revenue', views.get_monthly_revenue, name='get_revenue'),
    path('api/get_subscriptions/', views.get_subscriptions, name='get_subscriptions'),
    
    ##---LANDNG PAGES-----
    path("FAQ", views.FAQ_view, name="FAQ"),
    path("TAC", views.terms_and_conditions_view, name="TAC"),
    path("privacy-policy", views.privacy_policy_view, name="privacyPolicy"),
    path("included-forms", views.included_forms_view, name="includedForms"),
    path("contact-mp", views.landing_contact_view, name="landingContact"),
    path("register", views.landingRegister, name="register"),
    path("login", views.login_view, name="Login"),
    path("register_company", views.registerCompany, name="companyReg"),
    path("logout", views.logout_view, name="Logout"),
    path("activate/<str:uidb64>/<str:token>/", views.activate_view, name="activate"),
    path("reset/<str:uidb64>/<str:token>/", views.reset_password_activate_view, name="reset"),
    path("request-password", views.request_password_view, name='requestPassword'),
    path("change-password", views.main_change_password, name='mainPasswordChange'),
    path("auth/verify_2fa", views.verify_2fa, name='verify_2fa'),
    path("resend_2fa_code/", views.resend_2fa_code, name="resend_2fa_code"),
    ##---SUPERVISOR PAGES-----
    path("register-main/<str:access_page>", views.register_view, name="Register"),
    path("facilitylist", views.facilityList, name="facilityList"),
    path("request-form", views.form_request_view, name='requestForm'),
    path('ajax/facilityList/companyFacilityInfo/', views.get_facility_form_data, name='get_facility_form_data'),
    path('set-facility/', views.set_facility, name='set_facility'),
    path("facility-form-settings/<str:fsID>/<str:packetID>/<str:formLabel>", views.facility_form_settings, name="facilityFormSettings"),
    path('form-select/add-forms', views.Add_Forms, name='addingForms'),
    path("profileEdits/<str:userID>", views.profile_edit_view, name="profileEdits"),
    path("password/", views.change_password, name='PasswordChange'),
    path('packet-form-select/<str:packet>', views.facilityForm, name='facilityForms'),
    path('ajax/packets/update-label/', views.update_packet_form_label, name="updateFormLabel"),
    ##--ACCOUNT SETTINGS-----
    path("account/", views.sup_account_view, name="Account"),
    path("account/update/<str:selector>", views.sup_update_account, name="accountUpdate"),
    path("account/facility-settings/<int:facilityID>/<str:selector>", views.sup_facility_settings, name="selectedFacilitySettings"),
    ##---BILLING
    path("billing/subscribe/", views.stripe_subscription_view, name="stripe_subscribe"),
    path('stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),
    path("billing/portal/", views.stripe_customer_portal, name="stripe_customer_portal"),
    path("billing/success/", views.stripe_success, name="stripe_success"),
    ##---OBSERVER PAGES-------
    path("facility-select/", views.facility_select_view, name="facilitySelect"),
    path("daily_battery_profile/<str:access_page>/<str:date>", views.daily_battery_profile_view, name="daily_battery_profile"),
    path("personel-signature/",views.signature, name="signature"),
    path('check-bat-profile/', views.check_bat_profile, name='set_facility'),
    ##---SHARED PAGES-----
    path('archive/', views.archive_view, name='archive'),
    path("corrective-action/search/", views.corrective_action_view, name="Corrective-Action"),
    path("corrective-action/issues_view/<int:issueID>/<str:access_page>", views.issues_view, name="issues_view"),
    path("sop/", views.sop_view, name="Sop"),
    path("schedule_view/", views.schedule_view, name="Schedule"),
    path("schedule/<int:year>/<str:month>", views.calendar_view, name="Calendar"),
    path("contacts", views.shared_contacts_view, name="Contacts"),
    path("progress/<str:section>", views.formsProgress, name="Progress"),
    path('print-select/', views.printSelect, name='PrintSelect'),
    path('print-select-calendar/<str:type>/<str:forms>/<int:year>/<int:month>', views.calSelect, name='CalSelect'),
    path('print-index/<str:type>/<str:formGroup>/<str:formIdentity>/<str:formDate>', views.form_PDF, name='printIndex'),
    path("profile/<str:access_page>", views.profile, name="profile"),
    path("add_event/", views.event_add_view, name="Add Event"),
    ##------AJAX
    path('ajax/card/progress/', views.card_progress_bar, name='card_progress_bar'),
    path('ajax/card/daily-forms/', views.card_daily_battery_forms, name='card_daily_battery_forms'),
    path('ajax/card/graphs/', views.card_graphs, name='card_graphs'),
    path('ajax/card/corrective-actions/', views.card_corrective_actions, name='card_corrective_actions'),
    path('ajax/card/info/', views.card_info, name='card_info'),
    path('ajax/card/90DayPushTravels/', views.card_90DayPushTravels, name='card_90DayPushTravels'),
    path('ajax/card/contacts/', views.card_contacts, name='card_contacts'),
    path('ajax/sidebar/', views.sidebar_data, name='sidebar_data'),
    path('ajax/header/', views.header_data, name='header_data'),
    path("ajax/notification-count/", views.get_unread_notification_count, name="notification_count"),
    path("ajax/event-calendar/", views.ajax_calendar, name="ajax_calendar"),
    path("ajax/events-for-day/", views.events_for_day, name="events_for_day"),
    ##---FORMS
    path("form/Daily/1/<int:fsID>/<str:selector>", views.form1, name="form1"),
    path("form/Daily/2/<int:fsID>/<str:selector>", views.form2, name="form2"),
    path("form/Daily/3/<int:fsID>/<str:selector>", views.form3, name="form3"),
    path("form/Daily/4/<int:fsID>/<str:selector>", views.form4, name="form4"),
    path("form/Daily/5/<int:fsID>/<str:selector>", views.form5, name="form5"),
    path("form/Daily/6/<int:fsID>/<str:selector>", views.form6, name="form6"),
    path("form/Daily/7/<int:fsID>/<str:selector>", views.form7, name="form7"),
    path("form/Weekly/8/<int:fsID>/<str:selector>", views.form8, name="form8"),
    path("form/Daily/9/<int:fsID>/<str:selector>", views.form9, name="form9"),
    path("form/Weekly/F1/<int:fsID>/<str:selector>", views.formF1, name="formF1"),
    path("form/Weekly/F2/<int:fsID>/<str:selector>", views.formF2, name="formF2"),
    path("form/Weekly/F3/<int:fsID>/<str:selector>", views.formF3, name="formF3"),
    path("form/Weekly/F4/<int:fsID>/<str:selector>", views.formF4, name="formF4"),
    path("form/Weekly/F5/<int:fsID>/<str:selector>", views.formF5, name="formF5"),
    path("form/Weekly/F6/<int:fsID>/<str:selector>", views.formF6, name="formF6"),
    path("form/Weekly/F7/<int:fsID>/<str:selector>", views.formF7, name="formF7"),
    path("form/Weekly/17/<int:fsID>/<str:selector>", views.form17, name="form17"),
    path("form/Monthly/18/<int:fsID>/<str:selector>", views.form18, name="form18"),
    path("form/Weekly/19/<int:fsID>/<str:selector>", views.form19, name="form19"),
    path("form/Daily/20/<int:fsID>/<str:selector>", views.form20, name="form20"),
    path("form/Daily/21/<int:fsID>/<str:selector>", views.form21, name="form21"),
    path("form/Daily/22/<int:fsID>/<str:selector>", views.form22, name="form22"),
    path("form/Monthly/23/<int:fsID>/<str:selector>", views.form23, name="form23"),
    path("form/Daily/24/<int:fsID>/<str:selector>/<str:weekend_day>", views.form24, name="form24"),
    path("form/Daily/25/<int:fsID>/<str:selector>/<str:weekend_day>", views.form25, name="form25"),
    path("form/Monthly/26/inventory/<int:fsID>/<str:month>/<int:skNumber>/<str:selector>", views.form26, name="form26"),
    path("form/Quarterly/27/<int:fsID>/<str:selector>", views.form27, name="form27"),
    path("form/Monthly/29/<int:fsID>/<str:selector>", views.form29, name="form29"),
    path("form/Weekly/30/<int:fsID>/<str:selector>", views.form30, name="form30"),
    path("form/Monthly/31/<int:fsID>/<str:selector>", views.form31, name="form31"),
    path("api/get-inop/", views.inop_check_form_1, name="get-inop"),
    path("get-existing-form/", views.get_existing_form, name="get_existing_form"),
    path("get-submitted-areas/", views.get_submitted_areas, name="get_submitted_areas"),
    ##---COKE_BATTERY_DATA
    path("analytics/battery/push-travel-90-days/<str:facility>", views.pt_admin1_view, name="pt_admin1"),
    path("method303-rolling-avg/", views.method303_rolling_avg, name="rolling_avg"),
    


    

    
    ##----OTHER-------NOT CHANGED
    path("<str:facility>/DeleteProf/<str:profile_pic_id>", views.delete_prof_pic_view, name="DeleteProf"),
    path('<str:facility>/about', views.about_view, name='about'),
    path('safety', views.safety_view, name='safety'),
    path('<str:facility>/settings', views.settings_view, name='settings'),
    ##---SHARED PAGES-----NOT CHANGED
    
    path("<str:facility>/event_detail/<int:event_id>/<str:access_page>", views.event_detail_view, name="Event Details"),
    path('delete_selected_sops/<str:facility>/', views.delete_selected_sops, name='delete_selected_sops'),
    path("<str:facility>/DeleteSop/<str:sop_id>", views.delete_sop_view, name="DeleteSop"),
    path("<str:facility>/UpdateSop/<str:sop_id>", views.update_sop_view, name="UpdateSop"),
    #path('search_forms/<str:facility>/<str:access_page>/', views.search_forms_view, name='search_forms'),
    ##---DATA PAGES-----NOT CHANGED
    path("weekly_forms", views.weekly_forms, name="weekly_forms"),
    path("<str:facility>/pt_mth_input", views.pt_mth_input, name="pt_mth_input"),
    path("admin_data", views.admin_data_view, name="admin_data"),
    # path("pdf/<form>/<date>/", views.render_pdf_view, name="formA1_pdf"),
    # path("calendar", views.CalendarView.as_view(), name='calendar'),
    # path('pdf_view', views.render_pdf_view, name="pdf_view"),
    #path('pdf_view/', views.ViewPDF.as_view(), name="pdf_view"),
    #path('pdf_download/', views.DownloadPDF.as_view(), name="pdf_download"),
]
