# Generated by Django 3.2.4 on 2021-06-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0003_auto_20210625_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='subC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('truck_area', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=30)),
                ('stop_time', models.CharField(max_length=30)),
                ('readings', models.CharField(max_length=30)),
                ('observer', models.CharField(max_length=30)),
                ('cert_date', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=30)),
                ('issues', models.CharField(max_length=30)),
                ('cor_action', models.CharField(max_length=30)),
                ('notified', models.CharField(max_length=30)),
                ('time_date', models.CharField(max_length=30)),
            ],
        ),
    ]
