# Generated by Django 3.2.4 on 2021-06-25 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0004_subc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pushtravels',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subc',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subc',
            name='truck_area',
            field=models.CharField(choices=[('area', 'Area'), ('truck', 'Truck')], max_length=5),
        ),
    ]
