# Generated by Django 3.2.4 on 2021-06-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0005_auto_20210625_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushtravels',
            name='date',
        ),
        migrations.AlterField(
            model_name='forms',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subc',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subc',
            name='truck_area',
            field=models.CharField(choices=[('stick', 'wood'), ('bone', 'chicken')], max_length=5),
        ),
    ]
