# Generated by Django 3.2.4 on 2021-06-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0006_auto_20210625_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subc',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='subc',
            name='truck_area',
            field=models.CharField(choices=[('area', 'Area'), ('truck', 'Truck')], max_length=5),
        ),
    ]
