# Generated by Django 3.2.4 on 2021-06-26 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0007_auto_20210626_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subc',
            old_name='readings',
            new_name='area_readings',
        ),
        migrations.RenameField(
            model_name='subc',
            old_name='start_time',
            new_name='area_start_time',
        ),
        migrations.RenameField(
            model_name='subc',
            old_name='stop_time',
            new_name='area_stop_time',
        ),
        migrations.RenameField(
            model_name='subc',
            old_name='title',
            new_name='truck_readings',
        ),
        migrations.RemoveField(
            model_name='subc',
            name='truck_area',
        ),
        migrations.AddField(
            model_name='subc',
            name='area_sel',
            field=models.CharField(choices=[('panther eagle', 'Panther Eagle'), ('kepler', 'Kepler'), ('rock lick', 'Rock Lick'), ('mcclure', 'McClure'), ('elk valley', 'Elk Valley')], default='(select)', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subc',
            name='truck_sel',
            field=models.CharField(choices=[('#5', 'Truck #5'), ('#6', 'Truck #6'), ('#7', 'Truck #7'), ('#9', 'Truck #9'), ('contractor', 'Contractor'), ('dozer', 'Dozer')], default='(select)', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subc',
            name='truck_start_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subc',
            name='truck_stop_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subc',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
