# Generated by Django 3.2.4 on 2021-06-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0008_auto_20210626_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subc',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
