# Generated by Django 3.2.4 on 2021-06-26 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0010_alter_subc_truck_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCReadings',
            fields=[
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.subc')),
                ('TRead1', models.CharField(max_length=2)),
                ('TRead2', models.CharField(max_length=2)),
                ('TRead3', models.CharField(max_length=2)),
                ('TRead4', models.CharField(max_length=2)),
                ('TRead5', models.CharField(max_length=2)),
                ('TRead6', models.CharField(max_length=2)),
                ('TRead7', models.CharField(max_length=2)),
                ('TRead8', models.CharField(max_length=2)),
                ('TRead9', models.CharField(max_length=2)),
                ('TRead10', models.CharField(max_length=2)),
                ('TRead11', models.CharField(max_length=2)),
                ('TRead12', models.CharField(max_length=2)),
                ('ARead1', models.CharField(max_length=2)),
                ('ARead2', models.CharField(max_length=2)),
                ('ARead3', models.CharField(max_length=2)),
                ('ARead4', models.CharField(max_length=2)),
                ('ARead5', models.CharField(max_length=2)),
                ('ARead6', models.CharField(max_length=2)),
                ('ARead7', models.CharField(max_length=2)),
                ('ARead8', models.CharField(max_length=2)),
                ('ARead9', models.CharField(max_length=2)),
                ('ARead10', models.CharField(max_length=2)),
                ('ARead11', models.CharField(max_length=2)),
                ('ARead12', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='subc',
            name='area_readings',
        ),
        migrations.RemoveField(
            model_name='subc',
            name='truck_readings',
        ),
        migrations.AlterField(
            model_name='subc',
            name='area_start_time',
            field=models.TimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subc',
            name='area_stop_time',
            field=models.TimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subc',
            name='truck_stop_time',
            field=models.TimeField(max_length=30),
        ),
    ]
