# Generated by Django 3.2.4 on 2021-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0011_auto_20210626_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_num', models.CharField(max_length=30)),
                ('total_ovens', models.CharField(max_length=30)),
                ('facility_name', models.CharField(max_length=30)),
                ('County', models.CharField(max_length=30)),
                ('estab_num', models.CharField(max_length=30)),
                ('equip_location', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('process_equip1', models.CharField(max_length=30)),
                ('process_equip2', models.CharField(max_length=30)),
                ('op_mode1', models.CharField(max_length=30)),
                ('op_mode2', models.CharField(max_length=30)),
                ('emission_point', models.CharField(max_length=30)),
                ('bat_height', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyBatteryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreman', models.CharField(max_length=30)),
                ('crew', models.CharField(max_length=1)),
                ('inop_ovens', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('cer_date', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead10',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead11',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead12',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead4',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead5',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead6',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead7',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead8',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='ARead9',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead10',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead11',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead12',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead4',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead5',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead6',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead7',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead8',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='formcreadings',
            name='TRead9',
            field=models.CharField(max_length=3),
        ),
    ]
