# Generated by Django 3.2.4 on 2021-06-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0012_auto_20210626_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_battery_profile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreman', models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Lopez', 'Lopez')], max_length=10)),
                ('crew', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('inop_ovens', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='BatteryInfo',
            new_name='bat_info_model',
        ),
        migrations.DeleteModel(
            name='DailyBatteryProfile',
        ),
        migrations.DeleteModel(
            name='login_model',
        ),
    ]
