# Generated by Django 3.2.4 on 2021-06-27 04:02

from django.db import migrations, models
import django.utils.timezone



class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0013_auto_20210627_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='date_log',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='inop_ovens',
            field=models.CharField(max_length=2),
        ),
    ]
