# Generated by Django 3.2.4 on 2021-06-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0015_alter_daily_battery_profile_model_date_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='date_log',
            field=models.DateField(auto_now_add=True),
        ),
    ]
