# Generated by Django 3.2.4 on 2021-06-27 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0016_alter_daily_battery_profile_model_date_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_battery_profile_model',
            name='date_log',
        ),
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='date_save',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
