# Generated by Django 3.2.4 on 2021-06-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0018_auto_20210627_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_battery_profile_model',
            old_name='date_log',
            new_name='date_save',
        ),
    ]
