# Generated by Django 3.2.4 on 2021-06-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0019_rename_date_log_daily_battery_profile_model_date_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='date_save',
            field=models.DateField(),
        ),
    ]
