# Generated by Django 3.2.4 on 2021-06-27 04:35

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0021_alter_daily_battery_profile_model_date_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='date_save',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
