# Generated by Django 3.2.4 on 2021-06-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0023_alter_daily_battery_profile_model_date_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_battery_profile_model',
            name='date_save',
        ),
        migrations.RemoveField(
            model_name='subc',
            name='date',
        ),
    ]
