# Generated by Django 3.2.4 on 2021-06-27 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0024_auto_20210627_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='date_save',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subc',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
