# Generated by Django 3.2.4 on 2021-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0030_auto_20210630_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='subA5_readings_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o1', models.CharField(max_length=2)),
                ('o1_start', models.CharField(max_length=30)),
                ('o1_stop', models.CharField(max_length=30)),
                ('o1_16_reads', models.CharField(max_length=30)),
                ('o1_highest_opacity', models.CharField(max_length=30)),
                ('o1_instant_over_20', models.CharField(max_length=30)),
                ('o1_average_6', models.CharField(max_length=30)),
                ('o1_average_6_over_35', models.CharField(max_length=30)),
                ('o2', models.CharField(max_length=2)),
                ('o2_start', models.CharField(max_length=30)),
                ('o2_stop', models.CharField(max_length=30)),
                ('o2_16_reads', models.CharField(max_length=30)),
                ('o2_highest_opacity', models.CharField(max_length=30)),
                ('o2_instant_over_20', models.CharField(max_length=30)),
                ('o2_average_6', models.CharField(max_length=30)),
                ('o2_average_6_over_35', models.CharField(max_length=30)),
                ('o3', models.CharField(max_length=2)),
                ('o3_start', models.CharField(max_length=30)),
                ('o3_stop', models.CharField(max_length=30)),
                ('o3_16_reads', models.CharField(max_length=30)),
                ('o3_highest_opacity', models.CharField(max_length=30)),
                ('o3_instant_over_20', models.CharField(max_length=30)),
                ('o3_average_6', models.CharField(max_length=30)),
                ('o3_average_6_over_35', models.CharField(max_length=30)),
                ('o4', models.CharField(max_length=2)),
                ('o4_start', models.CharField(max_length=30)),
                ('o4_stop', models.CharField(max_length=30)),
                ('o4_16_reads', models.CharField(max_length=30)),
                ('o4_highest_opacity', models.CharField(max_length=30)),
                ('o4_instant_over_20', models.CharField(max_length=30)),
                ('o4_average_6', models.CharField(max_length=30)),
                ('o4_average_6_over_35', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_16_reads',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_stop',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_16_reads',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_stop',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_16_reads',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_stop',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_16_reads',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_stop',
        ),
        migrations.AddField(
            model_name='suba5_model',
            name='describe_background_stop',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='ambient_temp_start',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='ambient_temp_stop',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='humidity',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='plume_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Fugative', 'Fugative'), ('Continuous', 'Continuous'), ('Intermittent', 'Intermittent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='water_drolet_present',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='water_droplet_plume',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Attached', 'Attached'), ('Detached', 'Detached')], max_length=30),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='wind_direction',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='wind_speed_start',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='wind_speed_stop',
            field=models.CharField(max_length=4),
        ),
    ]
