# Generated by Django 3.2.4 on 2021-06-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0031_auto_20210630_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suba5_model',
            name='describe_emissions_point_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='describe_emissions_point_stop',
        ),
    ]
