# Generated by Django 3.2.4 on 2021-06-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0034_alter_suba5_readings_model_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o1_stop',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o2_stop',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o3_stop',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_average_6',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_average_6_over_35',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_highest_opacity',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_instant_over_20',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_start',
        ),
        migrations.RemoveField(
            model_name='suba5_model',
            name='o4_stop',
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o1',
            field=models.CharField(default='N/A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o1_average_6',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o1_average_6_over_35',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o1_highest_opacity',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o1_instant_over_20',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o1_start',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o1_stop',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o2',
            field=models.CharField(default='N/A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o2_average_6',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o2_average_6_over_35',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o2_highest_opacity',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o2_instant_over_20',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o2_start',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o2_stop',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o3',
            field=models.CharField(default='N/A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o3_average_6',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o3_average_6_over_35',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o3_highest_opacity',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o3_instant_over_20',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o3_start',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o3_stop',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o4',
            field=models.CharField(default='N/A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o4_average_6',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o4_average_6_over_35',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o4_highest_opacity',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o4_instant_over_20',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o4_start',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='o4_stop',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
    ]
