# Generated by Django 3.2.4 on 2021-06-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0035_auto_20210630_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suba5_readings_model',
            name='date',
        ),
    ]
