# Generated by Django 3.2.4 on 2021-06-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0036_remove_suba5_readings_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suba5_readings_model',
            name='date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='EES_Forms.suba5_model'),
        ),
    ]
