# Generated by Django 3.2.4 on 2021-06-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0037_suba5_readings_model_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suba5_readings_model',
            name='date',
        ),
        migrations.RemoveField(
            model_name='suba5_readings_model',
            name='id',
        ),
        migrations.AddField(
            model_name='suba5_readings_model',
            name='form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.suba5_model'),
            preserve_default=False,
        ),
    ]
