# Generated by Django 3.2.4 on 2021-07-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0040_rename_penis_suba5_readings_model_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='subA1_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('crew', models.CharField(max_length=30)),
                ('foreman', models.CharField(max_length=30)),
                ('start', models.CharField(max_length=30)),
                ('stop', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subA1_readings_model',
            fields=[
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.suba1_model')),
                ('c1_no', models.CharField(max_length=30)),
                ('c2_no', models.CharField(max_length=30)),
                ('c3_no', models.CharField(max_length=30)),
                ('c4_no', models.CharField(max_length=30)),
                ('c5_no', models.CharField(max_length=30)),
                ('c1_start', models.CharField(max_length=30)),
                ('c2_start', models.CharField(max_length=30)),
                ('c3_start', models.CharField(max_length=30)),
                ('c4_start', models.CharField(max_length=30)),
                ('c5_start', models.CharField(max_length=30)),
                ('c1_stop', models.CharField(max_length=30)),
                ('c2_stop', models.CharField(max_length=30)),
                ('c3_stop', models.CharField(max_length=30)),
                ('c4_stop', models.CharField(max_length=30)),
                ('c5_stop', models.CharField(max_length=30)),
                ('c1_sec', models.CharField(max_length=30)),
                ('c2_sec', models.CharField(max_length=30)),
                ('c3_sec', models.CharField(max_length=30)),
                ('c4_sec', models.CharField(max_length=30)),
                ('c5_sec', models.CharField(max_length=30)),
                ('c1_comments', models.CharField(max_length=30)),
                ('c2_comments', models.CharField(max_length=30)),
                ('c3_comments', models.CharField(max_length=30)),
                ('c4_comments', models.CharField(max_length=30)),
                ('c5_comments', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=30)),
            ],
        ),
    ]
