# Generated by Django 3.2.4 on 2021-07-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0041_suba1_model_suba1_readings_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='suba1_readings_model',
            name='larry_car',
            field=models.CharField(default='N/A', max_length=30),
            preserve_default=False,
        ),
    ]
