# Generated by Django 3.2.4 on 2021-07-06 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0042_suba1_readings_model_larry_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='pt_admin1_model',
            fields=[
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.suba5_readings_model')),
                ('add_days', models.DateTimeField(default=datetime.datetime(2021, 10, 4, 17, 15, 58, 883697))),
                ('days_left', models.DateTimeField(default=datetime.datetime(2021, 7, 16, 17, 15, 58, 883712))),
            ],
        ),
        migrations.DeleteModel(
            name='PushTravels',
        ),
        migrations.AlterField(
            model_name='forms',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='foobar', serialize=False, to='EES_Forms.suba5_model'),
        ),
    ]
