# Generated by Django 3.2.4 on 2021-07-07 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0043_auto_20210706_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='formD_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('truck_id1', models.CharField(max_length=30)),
                ('date1', models.CharField(max_length=30)),
                ('time1', models.CharField(max_length=30)),
                ('contents1', models.CharField(max_length=30)),
                ('freeboard1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('wetted1', models.CharField(max_length=30)),
                ('comments1', models.CharField(max_length=30)),
                ('truck_id2', models.CharField(max_length=30)),
                ('date2', models.CharField(max_length=30)),
                ('time2', models.CharField(max_length=30)),
                ('contents2', models.CharField(max_length=30)),
                ('freeboard2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('wetted2', models.CharField(max_length=30)),
                ('comments2', models.CharField(max_length=30)),
                ('truck_id3', models.CharField(max_length=30)),
                ('date3', models.CharField(max_length=30)),
                ('time3', models.CharField(max_length=30)),
                ('contents3', models.CharField(max_length=30)),
                ('freeboard3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('wetted3', models.CharField(max_length=30)),
                ('comments3', models.CharField(max_length=30)),
                ('truck_id4', models.CharField(max_length=30)),
                ('date4', models.CharField(max_length=30)),
                ('time4', models.CharField(max_length=30)),
                ('contents4', models.CharField(max_length=30)),
                ('freeboard4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('wetted4', models.CharField(max_length=30)),
                ('comments4', models.CharField(max_length=30)),
                ('truck_id5', models.CharField(max_length=30)),
                ('date5', models.CharField(max_length=30)),
                ('time5', models.CharField(max_length=30)),
                ('contents5', models.CharField(max_length=30)),
                ('freeboard5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('wetted5', models.CharField(max_length=30)),
                ('comments5', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 12, 5, 59, 576214)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 12, 5, 59, 576229)),
        ),
    ]
