# Generated by Django 3.2.4 on 2021-07-07 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0044_auto_20210707_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id1',
            field=models.CharField(choices=[('#5', 'Attached'), ('#6', 'Attached'), ('#7', 'Attached'), ('#9', 'Attached'), ('Dozer', 'Attached'), ('Semi', 'Attached'), ('Contractor', 'Attached')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 12, 22, 20, 127402)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 12, 22, 20, 127416)),
        ),
    ]
