# Generated by Django 3.2.4 on 2021-07-07 17:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0045_auto_20210707_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formd_model',
            name='month',
        ),
        migrations.AddField(
            model_name='formd_model',
            name='week_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formd_model',
            name='week_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents1',
            field=models.CharField(choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents2',
            field=models.CharField(choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents3',
            field=models.CharField(choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents4',
            field=models.CharField(choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents5',
            field=models.CharField(choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date3',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date4',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date5',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id1',
            field=models.CharField(choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id2',
            field=models.CharField(choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id3',
            field=models.CharField(choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id4',
            field=models.CharField(choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id5',
            field=models.CharField(choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted1',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted2',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted3',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted4',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted5',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 13, 53, 54, 586911)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 13, 53, 54, 586925)),
        ),
    ]
