# Generated by Django 3.2.4 on 2021-07-07 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0046_auto_20210707_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formd_model',
            name='comments1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='comments2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='comments3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='comments4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='comments5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents1',
            field=models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents2',
            field=models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents3',
            field=models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents4',
            field=models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='contents5',
            field=models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='date5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='freeboard1',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='freeboard2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='freeboard3',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='freeboard4',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='freeboard5',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id1',
            field=models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id2',
            field=models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id3',
            field=models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id4',
            field=models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='truck_id5',
            field=models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted1',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted2',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted3',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted4',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='wetted5',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 13, 16, 49982)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 13, 16, 49998)),
        ),
    ]
