# Generated by Django 3.2.4 on 2021-07-07 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0047_auto_20210707_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formd_model',
            name='week_end',
            field=models.DateField(default=datetime.date(2021, 7, 9)),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='week_start',
            field=models.DateField(default=datetime.date(2021, 7, 3)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 19, 46, 995531)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 19, 46, 995546)),
        ),
    ]
