# Generated by Django 3.2.4 on 2021-07-07 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0050_auto_20210707_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formd_model',
            name='week_end',
            field=models.DateField(default=datetime.date(2021, 7, 9), null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='week_start',
            field=models.DateField(default=datetime.date(2021, 7, 3), null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 18, 19, 8, 878421)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 18, 19, 8, 878435)),
        ),
    ]
