# Generated by Django 3.2.4 on 2021-07-08 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0055_auto_20210707_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='formE_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('crew', models.CharField(max_length=30)),
                ('foreman', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=30)),
                ('end_time', models.CharField(max_length=30)),
                ('leaks', models.CharField(max_length=30)),
                ('oven1', models.CharField(max_length=30)),
                ('time1', models.CharField(max_length=30)),
                ('source1', models.CharField(max_length=30)),
                ('comments1', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 21, 41, 22, 886016)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 21, 41, 22, 886030)),
        ),
    ]
