# Generated by Django 3.2.4 on 2021-07-08 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0056_auto_20210707_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forme_model',
            name='crew',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Lopez', 'Lopez')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='leaks',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='oven1',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='source1',
            field=models.CharField(choices=[('Inspection Cap', 'Inspection Cap'), ('GooseNeck', 'GooseNeck'), ('Flange', 'Flange'), ('Expansion Joint', 'Expansion Joint')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='time1',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 22, 28, 30, 845281)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 22, 28, 30, 845296)),
        ),
    ]
