# Generated by Django 3.2.4 on 2021-07-08 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0059_auto_20210707_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='formI_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('time_0', models.CharField(max_length=30)),
                ('time_1', models.CharField(max_length=30)),
                ('time_2', models.CharField(max_length=30)),
                ('time_3', models.CharField(max_length=30)),
                ('time_4', models.CharField(max_length=30)),
                ('obser_0', models.CharField(max_length=30)),
                ('obser_1', models.CharField(max_length=30)),
                ('obser_2', models.CharField(max_length=30)),
                ('obser_3', models.CharField(max_length=30)),
                ('obser_4', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 23, 46, 55, 56277)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 23, 46, 55, 56293)),
        ),
    ]
