# Generated by Django 3.2.4 on 2021-07-08 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0060_auto_20210707_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='formL_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('time_0', models.CharField(max_length=30)),
                ('time_1', models.CharField(max_length=30)),
                ('time_2', models.CharField(max_length=30)),
                ('time_3', models.CharField(max_length=30)),
                ('time_4', models.CharField(max_length=30)),
                ('time_5', models.CharField(max_length=30)),
                ('time_6', models.CharField(max_length=30)),
                ('obser_0', models.CharField(max_length=30)),
                ('obser_1', models.CharField(max_length=30)),
                ('obser_2', models.CharField(max_length=30)),
                ('obser_3', models.CharField(max_length=30)),
                ('obser_4', models.CharField(max_length=30)),
                ('obser_5', models.CharField(max_length=30)),
                ('obser_6', models.CharField(max_length=30)),
                ('vents_0', models.CharField(max_length=30)),
                ('vents_1', models.CharField(max_length=30)),
                ('vents_2', models.CharField(max_length=30)),
                ('vents_3', models.CharField(max_length=30)),
                ('vents_4', models.CharField(max_length=30)),
                ('vents_5', models.CharField(max_length=30)),
                ('vents_6', models.CharField(max_length=30)),
                ('mixer_0', models.CharField(max_length=30)),
                ('mixer_1', models.CharField(max_length=30)),
                ('mixer_2', models.CharField(max_length=30)),
                ('mixer_3', models.CharField(max_length=30)),
                ('mixer_4', models.CharField(max_length=30)),
                ('mixer_5', models.CharField(max_length=30)),
                ('mixer_6', models.CharField(max_length=30)),
                ('v_comments_0', models.CharField(max_length=30)),
                ('v_comments_1', models.CharField(max_length=30)),
                ('v_comments_2', models.CharField(max_length=30)),
                ('v_comments_3', models.CharField(max_length=30)),
                ('v_comments_4', models.CharField(max_length=30)),
                ('v_comments_5', models.CharField(max_length=30)),
                ('v_comments_6', models.CharField(max_length=30)),
                ('m_comments_0', models.CharField(max_length=30)),
                ('m_comments_1', models.CharField(max_length=30)),
                ('m_comments_2', models.CharField(max_length=30)),
                ('m_comments_3', models.CharField(max_length=30)),
                ('m_comments_4', models.CharField(max_length=30)),
                ('m_comments_5', models.CharField(max_length=30)),
                ('m_comments_6', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 0, 25, 2, 812236)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 0, 25, 2, 812251)),
        ),
    ]
