# Generated by Django 3.2.4 on 2021-07-09 02:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0062_auto_20210708_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='formM_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('paved', models.CharField(choices=[('#4 Booster Station', '#4 Booster Station'), ('#5 Battery Road', '#5 Battery Road'), ('Coal Dump Horseshoe', 'Coal Dump Horseshoe'), ('Coal Handling Road (Partial)', 'Coal Handling Road (Partial)'), ('Coke Plant Road', 'Coke Plant Road'), ('Coke Plant Mech Road', 'Coke Plant Mech Road'), ('North Gate Area', 'North Gate Area'), ('Compund Road', 'Compund Road'), ('D-4 Blast Furnace Road', 'D-4 Blast Furnace Road'), ('Gap Gate Road', 'Gap Gate Road'), ('#3 Ore Dock Road', '#3 Ore Dock Road'), ('River Road', 'River Road'), ('Weigh Station Road', 'Weigh Station Road'), ('Zug Island Road', 'Zug Island Road')], max_length=30)),
                ('pav_start', models.TimeField(blank=True, null=True)),
                ('pav_stop', models.TimeField(blank=True, null=True)),
                ('unpaved', models.CharField(choices=[('North Gate Truck Turn', 'North Gate Truck Turn'), ('Screening Station Road', 'Screening Station Road'), ('Coal Handling Road (Partial)', 'Coal Handling Road (Partial)'), ('Taj Mahal Road', 'Taj Mahal Road'), ('PECS Approach', 'PECS Approach'), ('No. 2 Boilerhouse Road', 'No. 2 Boilerhouse Road')], max_length=30)),
                ('unp_start', models.TimeField(blank=True, null=True)),
                ('unp_stop', models.TimeField(blank=True, null=True)),
                ('parking', models.CharField(choices=[('Gap Gate Parking', 'Gap Gate Parking'), ('Truck Garage Area', 'Truck Garage Area'), ('EES Coke Office Parking', 'EES Coke Office Parking')], max_length=30)),
                ('par_start', models.TimeField(blank=True, null=True)),
                ('par_stop', models.TimeField(blank=True, null=True)),
                ('storage', models.CharField(choices=[('Area B Coke Storage Piles', 'Area B Coke Storage Piles'), ('EES Coke Coal Storage Piles', 'EES Coke Coal Storage Piles')], max_length=30)),
                ('sto_start', models.TimeField(blank=True, null=True)),
                ('sto_stop', models.TimeField(blank=True, null=True)),
                ('observer', models.CharField(max_length=30)),
                ('cert_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='forms',
            name='date',
        ),
        migrations.AddField(
            model_name='forms',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 22, 22, 16, 179613)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 22, 22, 16, 179630)),
        ),
    ]
