# Generated by Django 3.2.4 on 2021-07-10 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0065_auto_20210709_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='formA2_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True)),
                ('inop_ovens', models.CharField(max_length=2)),
                ('crew', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('foreman', models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Lopez', 'Lopez')], max_length=30)),
                ('p_start', models.TimeField(blank=True)),
                ('p_stop', models.TimeField(blank=True)),
                ('c_start', models.TimeField(blank=True)),
                ('c_stop', models.TimeField(blank=True)),
                ('p_leak_oven1', models.CharField(max_length=2)),
                ('p_leak_loc1', models.CharField(choices=[('Door', 'D'), ('Chuck Door', 'C'), ('Masonry', 'M')], max_length=30)),
                ('p_leak_zone1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=30)),
                ('c_leak_oven1', models.CharField(max_length=2)),
                ('c_leak_loc1', models.CharField(choices=[('Door', 'D'), ('Chuck Door', 'C'), ('Masonry', 'M')], max_length=30)),
                ('c_leak_zone1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=30)),
                ('p_temp_block_from', models.CharField(max_length=30)),
                ('p_temp_block_to', models.CharField(max_length=30)),
                ('c_temp_block_from', models.CharField(max_length=30)),
                ('c_temp_block_to', models.CharField(max_length=30)),
                ('p_traverse_time_min', models.CharField(max_length=30)),
                ('p_traverse_time_sec', models.CharField(max_length=30)),
                ('c_traverse_time_min', models.CharField(max_length=30)),
                ('c_traverse_time_sec', models.CharField(max_length=30)),
                ('total_traverse_time', models.CharField(max_length=30)),
                ('allowed_traverse_time', models.CharField(max_length=30)),
                ('valid_run', models.BooleanField(default=None)),
                ('leaking_doors', models.CharField(max_length=30)),
                ('doors_not_observed', models.CharField(max_length=30)),
                ('inop_doors', models.CharField(max_length=30)),
                ('percent_leaking', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='crew',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 1, 14, 45, 967441)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 1, 14, 45, 967487)),
        ),
        migrations.AlterField(
            model_name='suba1_model',
            name='crew',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='suba1_model',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Lopez', 'Lopez')], max_length=30),
        ),
        migrations.AlterField(
            model_name='suba1_model',
            name='start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_model',
            name='stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c1_no',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c1_sec',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c1_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c1_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c2_no',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c2_sec',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c2_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c2_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c3_no',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c3_sec',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c3_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c3_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c4_no',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c4_sec',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c4_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c4_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c5_no',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c5_sec',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c5_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='c5_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='comments',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='suba1_readings_model',
            name='larry_car',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=30),
        ),
    ]
