# Generated by Django 3.1.3 on 2021-07-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0065_auto_20210709_0052'),
        ('EES_Forms', '0052_auto_20210708_1449'),
    ]

    operations = [
    ]
