# Generated by Django 3.2.4 on 2021-07-10 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0066_auto_20210710_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma2_model',
            name='c_leak_loc1',
            field=models.CharField(blank=True, choices=[('Door', 'D'), ('Chuck Door', 'C'), ('Masonry', 'M')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='c_leak_oven1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='c_leak_zone1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='p_leak_loc1',
            field=models.CharField(blank=True, choices=[('Door', 'D'), ('Chuck Door', 'C'), ('Masonry', 'M')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='p_leak_oven1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='p_leak_zone1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 1, 22, 16, 204554)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 1, 22, 16, 204569)),
        ),
    ]
