# Generated by Django 3.2.4 on 2021-07-10 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0070_auto_20210710_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='formA3_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True)),
                ('inop_ovens', models.CharField(max_length=2)),
                ('crew', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('foreman', models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Lopez', 'Lopez')], max_length=30)),
                ('om_start', models.TimeField(blank=True)),
                ('om_stop', models.TimeField(blank=True)),
                ('l_start', models.TimeField(blank=True)),
                ('l_stop', models.TimeField(blank=True)),
                ('om_oven1', models.CharField(blank=True, max_length=2, null=True)),
                ('om_loc1', models.CharField(blank=True, choices=[('Dampered Off', 'D'), ('Cap', 'C'), ('Flange', 'F'), ('Slip Joint', 'S'), ('Base', 'B'), ('Piping', 'P'), ('Other', 'O'), ('Mini Standpipe', 'MS')], max_length=30, null=True)),
                ('l_oven1', models.CharField(blank=True, max_length=2, null=True)),
                ('l_loc1', models.CharField(blank=True, choices=[('Dampered Off', 'D'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=30, null=True)),
                ('om_traverse_time_min', models.CharField(max_length=30)),
                ('om_traverse_time_sec', models.CharField(max_length=30)),
                ('l_traverse_time_min', models.CharField(max_length=30)),
                ('l_traverse_time_sec', models.CharField(max_length=30)),
                ('om_allowed_traverse_time', models.CharField(max_length=30)),
                ('l_allowed_traverse_time', models.CharField(max_length=30)),
                ('om_valid_run', models.BooleanField(default=None)),
                ('l_valid_run', models.BooleanField(default=None)),
                ('om_leaks', models.CharField(max_length=30)),
                ('l_leaks', models.CharField(max_length=30)),
                ('om_not_observed', models.CharField(max_length=30)),
                ('l_not_observed', models.CharField(max_length=30)),
                ('om_percent_leaking', models.CharField(max_length=30)),
                ('l_percent_leaking', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 2, 39, 5, 159990)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 2, 39, 5, 160005)),
        ),
    ]
