# Generated by Django 3.2.4 on 2021-07-10 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0072_auto_20210710_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='formA4_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True)),
                ('crew', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('foreman', models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Lopez', 'Lopez')], max_length=30)),
                ('main_start', models.TimeField(blank=True)),
                ('main_stop', models.TimeField(blank=True)),
                ('main_1', models.CharField(max_length=30)),
                ('main_2', models.CharField(max_length=30)),
                ('main_3', models.CharField(max_length=30)),
                ('main_4', models.CharField(max_length=30)),
                ('suction_main', models.CharField(max_length=30)),
                ('oven_leak_1', models.CharField(max_length=2)),
                ('time_leak_1', models.TimeField(blank=True)),
                ('date_temp_seal_leak_1', models.DateField(blank=True)),
                ('time_temp_seal_leak_1', models.TimeField(blank=True)),
                ('temp_seal_by_leak_1', models.CharField(max_length=30)),
                ('date_init_repair_leak_1', models.DateField(blank=True)),
                ('time_init_repair_leak_1', models.TimeField(blank=True)),
                ('date_comp_repair_leak_1', models.DateField(blank=True)),
                ('time_comp_repair_leak_1', models.TimeField(blank=True)),
                ('comp_by_leak_1', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 12, 51, 59, 893531)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 12, 51, 59, 893546)),
        ),
    ]
