# Generated by Django 3.2.4 on 2021-07-10 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0073_auto_20210710_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma4_model',
            name='comp_by_leak_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='date_comp_repair_leak_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='date_init_repair_leak_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='date_temp_seal_leak_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='oven_leak_1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='temp_seal_by_leak_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='time_comp_repair_leak_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='time_init_repair_leak_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='time_leak_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='time_temp_seal_leak_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 13, 3, 43, 275258)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 13, 3, 43, 275272)),
        ),
    ]
