# Generated by Django 3.2.4 on 2021-07-10 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0074_auto_20210710_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='formd_model',
            name='observer1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formd_model',
            name='observer2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formd_model',
            name='observer3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formd_model',
            name='observer4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formd_model',
            name='observer5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formd_model',
            name='time5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 14, 4, 28, 773846)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 14, 4, 28, 773863)),
        ),
    ]
