# Generated by Django 3.2.4 on 2021-07-11 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0075_auto_20210710_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='formB_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('observer_0', models.CharField(max_length=30)),
                ('time_0', models.TimeField(blank=True)),
                ('weather_0', models.CharField(choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('snow', 'Snow'), ('excessive wind', 'Excessive Wind')], max_length=30)),
                ('wind_speed_0', models.CharField(max_length=3)),
                ('fugitive_dust_observed_0', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('supressant_applied_0', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('supressant_active_0', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('working_face_exceed_0', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('spills_0', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('pushed_back_0', models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('coal_vessel_0', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('water_sprays_0', models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('loader_lowered_0', models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('working_water_sprays_0', models.CharField(choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('barrier_thickness_0', models.CharField(choices=[('none', 'None'), ('0" - 1/4"', '0" - 1/4"'), ('1/4" - 1/2"', '1/4" - 1/2"'), ('1/2" - 3/4"', '1/2" - 3/4"'), ('3/4" - 1"', '3/4" - 1"'), ('1" - 2"', '1" - 2"')], max_length=30)),
                ('surface_quality_0', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=30)),
                ('surpressant_crust_0', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('additional_surpressant_0', models.DateField(blank=True)),
                ('comments_0', models.CharField(blank=True, max_length=30)),
                ('wharf_0', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=30)),
                ('breeze_0', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 0, 38, 55, 324461)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 0, 38, 55, 324475)),
        ),
    ]
