# Generated by Django 3.1.3 on 2021-07-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0075_auto_20210710_1404'),
        ('EES_Forms', '0066_merge_20210709_2359'),
    ]

    operations = [
    ]
