# Generated by Django 3.1.3 on 2021-07-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0078_auto_20210711_1632'),
        ('EES_Forms', '0077_auto_20210711_1401'),
    ]

    operations = [
    ]
