# Generated by Django 3.2.4 on 2021-07-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0077_auto_20210711_1401'),
        ('EES_Forms', '0078_auto_20210711_1632'),
    ]

    operations = [
    ]
