# Generated by Django 3.2.4 on 2021-07-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0079_merge_20210712_0042'),
        ('EES_Forms', '0081_auto_20210711_2349'),
    ]

    operations = [
    ]
