# Generated by Django 3.2.4 on 2021-07-12 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0084_auto_20210712_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formf2_model',
            name='action_7',
        ),
        migrations.RemoveField(
            model_name='formf2_model',
            name='comments_7',
        ),
        migrations.RemoveField(
            model_name='formf2_model',
            name='status_7',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 15, 11, 43, 897574)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 15, 11, 43, 897589)),
        ),
    ]
