# Generated by Django 3.2.4 on 2021-07-14 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0088_auto_20210713_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='profile_picture',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 22, 17, 12, 492138)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 22, 17, 12, 492154)),
        ),
    ]
