# Generated by Django 3.2.4 on 2021-07-14 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0090_auto_20210713_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='issues_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=30)),
                ('issues', models.CharField(max_length=30)),
                ('notified', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('cor_action', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 1, 44, 34, 405916)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 1, 44, 34, 405931)),
        ),
    ]
