# Generated by Django 3.2.4 on 2021-07-15 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0092_auto_20210714_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='issues_model',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 20, 45, 13, 48261)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 20, 45, 13, 48279)),
        ),
    ]
