# Generated by Django 3.2.4 on 2021-07-15 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0093_auto_20210714_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='issues_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=30)),
                ('issues', models.CharField(max_length=30)),
                ('notified', models.CharField(max_length=30)),
                ('time', models.TimeField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('cor_action', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 20, 55, 53, 866749)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 20, 55, 53, 866769)),
        ),
    ]
