# Generated by Django 3.2.4 on 2021-07-15 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0094_auto_20210714_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 16, 26, 668885)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 21, 16, 26, 668900)),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o1_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o1_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o2_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o2_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o3_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o3_stop',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o4_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o4_stop',
            field=models.TimeField(blank=True),
        ),
    ]
