# Generated by Django 3.2.4 on 2021-07-15 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0095_auto_20210714_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma2_model',
            name='doors_not_observed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='inop_doors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='inop_ovens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='leaking_doors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 40, 54, 661016)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 21, 40, 54, 661031)),
        ),
    ]
