# Generated by Django 3.2.4 on 2021-07-15 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0099_auto_20210714_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formb_model',
            name='additional_surpressant_0',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='additional_surpressant_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='additional_surpressant_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='additional_surpressant_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='additional_surpressant_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='comments_0',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='comments_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='comments_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='comments_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='comments_4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='time_0',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='time_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='time_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='time_4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='wind_speed_4',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 23, 30, 1, 899394)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 23, 30, 1, 899409)),
        ),
    ]
