# Generated by Django 3.2.4 on 2021-07-15 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0100_auto_20210714_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 18, 43, 17, 696813)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 18, 43, 17, 696828)),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o1_average_6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o2_average_6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o3_average_6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suba5_readings_model',
            name='o4_average_6',
            field=models.FloatField(),
        ),
    ]
