# Generated by Django 3.2.4 on 2021-07-15 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0101_auto_20210715_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 18, 47, 42, 353860)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 18, 47, 42, 353876)),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='estab',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='estab_no',
            field=models.CharField(max_length=5),
        ),
    ]
