# Generated by Django 3.2.4 on 2021-07-16 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0105_auto_20210716_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formb_model',
            name='observer_0',
            field=models.CharField(blank=True, choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 3, 50, 54, 808422)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 3, 50, 54, 808442)),
        ),
    ]
