# Generated by Django 3.2.4 on 2021-07-16 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0108_auto_20210716_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subc',
            name='cor_action',
        ),
        migrations.RemoveField(
            model_name='subc',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='subc',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='subc',
            name='time_date',
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='cor_action',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='issues',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 18, 8, 33, 732456)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 18, 8, 33, 732470)),
        ),
        migrations.AlterField(
            model_name='subc',
            name='cert_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subc',
            name='date',
            field=models.DateField(),
        ),
    ]
