# Generated by Django 3.2.4 on 2021-07-17 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0117_auto_20210716_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 20, 26, 30, 903214)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 20, 26, 30, 903230)),
        ),
        migrations.AlterField(
            model_name='subc',
            name='cert_date',
            field=models.DateField(),
        ),
    ]
