# Generated by Django 3.2.4 on 2021-07-17 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0119_auto_20210716_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forme_model',
            name='observer',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 21, 30, 40, 167424)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 21, 30, 40, 167438)),
        ),
        migrations.AlterField(
            model_name='subc',
            name='average_p',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subc',
            name='average_t',
            field=models.IntegerField(blank=True),
        ),
    ]
