# Generated by Django 3.2.4 on 2021-07-20 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0121_auto_20210718_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_1',
            field=models.CharField(blank=True, choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler'), ('TobiasAckerman', 'Tobias Ackerman')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_2',
            field=models.CharField(blank=True, choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler'), ('TobiasAckerman', 'Tobias Ackerman')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_3',
            field=models.CharField(blank=True, choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler'), ('TobiasAckerman', 'Tobias Ackerman')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_4',
            field=models.CharField(blank=True, choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler'), ('TobiasAckerman', 'Tobias Ackerman')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='cor_action',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='issues_model',
            name='issues',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 2, 20, 24, 242156)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 2, 20, 24, 242170)),
        ),
        migrations.AlterField(
            model_name='subc',
            name='observer',
            field=models.CharField(choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler'), ('TobiasAckerman', 'Tobias Ackerman')], max_length=30),
        ),
    ]
