# Generated by Django 3.2.5 on 2021-07-24 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0124_auto_20210720_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='header',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 20, 38, 52, 437905)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 20, 38, 52, 437919)),
        ),
    ]
