# Generated by Django 3.2.5 on 2021-07-24 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0125_auto_20210723_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formb_model',
            name='observer_0',
            field=models.CharField(blank=True, choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler'), ('TobiasAckerman', 'Tobias Ackerman')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 21, 23, 6, 434677)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 21, 23, 6, 434692)),
        ),
        migrations.AlterField(
            model_name='suba1_model',
            name='observer',
            field=models.CharField(choices=[('foo', 'Foo Bar'), ('aackerman', 'Anthony Ackerman'), ('kjanis', 'Kerra Janis'), ('tlicht', 'Tristian Licht'), ('BigPenis', 'Micah Trierweiler'), ('TobiasAckerman', 'Tobias Ackerman')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subc',
            name='observer',
            field=models.CharField(max_length=30),
        ),
    ]
