# Generated by Django 3.2.4 on 2021-07-28 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0133_auto_20210724_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('P', 'Primary'), ('BU', 'Back Up'), ('Off', 'Off'), ('Office', 'Office '), ('BH', 'BagHouses'), ('QT', 'Quarterly Trucks'), ('BH2-S', 'Boilerhouse Stacks')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forma3_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_0',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_1',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_2',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_3',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formb_model',
            name='observer_4',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='obser_0',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='obser_1',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='obser_2',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='obser_3',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='obser_4',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='time_0',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='time_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='time_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formi_model',
            name='time_4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 18, 50, 52, 179469)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 18, 50, 52, 179482)),
        ),
        migrations.AlterField(
            model_name='suba1_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='suba5_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subc',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
    ]
