# Generated by Django 3.2.4 on 2021-07-29 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0138_auto_20210729_0221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subC',
            new_name='formC_model',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 2, 23, 17, 690393)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 2, 23, 17, 690410)),
        ),
    ]
