# Generated by Django 3.2.4 on 2021-07-29 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0139_auto_20210729_0223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormCReadings',
            new_name='formC_readings_model',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 2, 24, 32, 51276)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 2, 24, 32, 51289)),
        ),
    ]
