# Generated by Django 3.2.4 on 2021-07-29 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0141_auto_20210729_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formh_model',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 16, 57, 43, 200294)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 16, 57, 43, 200307)),
        ),
    ]
