# Generated by Django 3.2.4 on 2021-07-30 19:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0142_auto_20210729_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='formG2_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('estab', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('estab_no', models.CharField(max_length=30)),
                ('equip_loc', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('observer', models.CharField(max_length=30)),
                ('cert_date', models.CharField(max_length=30)),
                ('process_equip1', models.CharField(max_length=50)),
                ('process_equip2', models.CharField(max_length=50)),
                ('op_mode1', models.CharField(max_length=30)),
                ('op_mode2', models.CharField(max_length=30)),
                ('background_color_start', models.CharField(max_length=30)),
                ('background_color_stop', models.CharField(max_length=30)),
                ('sky_conditions', models.CharField(max_length=30)),
                ('wind_speed_start', models.CharField(max_length=2)),
                ('wind_speed_stop', models.CharField(max_length=4)),
                ('wind_direction', models.CharField(max_length=3)),
                ('emission_point_start', models.CharField(max_length=50)),
                ('emission_point_stop', models.CharField(max_length=50)),
                ('ambient_temp_start', models.CharField(max_length=3)),
                ('ambient_temp_stop', models.CharField(max_length=4)),
                ('humidity', models.CharField(max_length=3)),
                ('height_above_ground', models.CharField(max_length=30)),
                ('height_rel_observer', models.CharField(max_length=30)),
                ('distance_from', models.CharField(max_length=30)),
                ('direction_from', models.CharField(max_length=30)),
                ('describe_emissions_start', models.CharField(max_length=30)),
                ('describe_emissions_stop', models.CharField(max_length=30)),
                ('emission_color_start', models.CharField(max_length=30)),
                ('emission_color_stop', models.CharField(max_length=30)),
                ('plume_type', models.CharField(choices=[('N/A', 'N/A'), ('Fugative', 'Fugative'), ('Continuous', 'Continuous'), ('Intermittent', 'Intermittent')], max_length=30)),
                ('water_drolet_present', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('water_droplet_plume', models.CharField(choices=[('N/A', 'N/A'), ('Attached', 'Attached'), ('Detached', 'Detached')], max_length=30)),
                ('plume_opacity_determined_start', models.CharField(max_length=50)),
                ('plume_opacity_determined_stop', models.CharField(max_length=50)),
                ('describe_background_start', models.CharField(max_length=30)),
                ('describe_background_stop', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='formm_model',
            name='comments',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='cert_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='par_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='par_stop',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='pav_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='pav_stop',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='sto_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='sto_stop',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='unp_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='unp_stop',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 15, 19, 53, 687753)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 15, 19, 53, 687765)),
        ),
    ]
