# Generated by Django 3.2.4 on 2021-07-31 21:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0143_auto_20210730_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='weekdays_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='week_end',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='week_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 17, 28, 26, 252413)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 17, 28, 26, 252427)),
        ),
    ]
