# Generated by Django 3.2.4 on 2021-07-31 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0144_auto_20210731_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='day_freq',
            field=models.CharField(choices=[('Any', 'Any'), ('0', 'Mondays'), ('1', 'Tuesdays'), ('2', 'Wednesdays'), ('3', 'Thursdays'), ('4', 'Fridays'), ('5', 'Saturdays'), ('6', 'Sundays')], default='Any', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 17, 54, 50, 78298)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 17, 54, 50, 78311)),
        ),
    ]
