# Generated by Django 3.2.4 on 2021-08-01 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0146_auto_20210731_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Final time', null=True, verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Starting time', null=True, verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='day_freq',
            field=models.CharField(choices=[('Any', 'Any'), ('0', 'Mondays'), ('1', 'Tuesdays'), ('2', 'Wednesdays'), ('3', 'Thursdays'), ('4', 'Fridays'), ('5', 'Saturdays'), ('6', 'Sundays')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 17, 17, 52, 582989)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 17, 17, 52, 583002)),
        ),
    ]
