# Generated by Django 3.2.4 on 2021-08-01 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0149_auto_20210801_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='weekend_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 18, 50, 40, 752893)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 18, 50, 40, 752907)),
        ),
    ]
