# Generated by Django 3.2.4 on 2021-08-02 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0150_auto_20210801_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='formO_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_6', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_7', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_8', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_9', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('comments', models.CharField(max_length=150)),
                ('actions_taken', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 20, 2, 39, 830328)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 20, 2, 39, 830341)),
        ),
    ]
