# Generated by Django 3.2.4 on 2021-08-02 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0151_auto_20210801_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='formo_model',
            name='observer',
            field=models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formo_model',
            name='comments',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 20, 19, 11, 646746)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 20, 19, 11, 646760)),
        ),
    ]
