# Generated by Django 3.2.4 on 2021-08-02 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0155_auto_20210801_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='formP_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('Q_1', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_2', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_4', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_5', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_6', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_7', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_8', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Q_9', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('comments', models.CharField(max_length=300)),
                ('actions_taken', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 51, 31, 589690)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 21, 51, 31, 589704)),
        ),
    ]
