# Generated by Django 3.2.4 on 2021-08-02 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0157_auto_20210801_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='formo_model',
            name='weekend_day',
            field=models.CharField(choices=[('5', 'Saturdays'), ('6', 'Sundays')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 22, 12, 15, 451596)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 22, 12, 15, 451610)),
        ),
    ]
