# Generated by Django 3.2.4 on 2021-08-02 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0159_auto_20210801_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forml_model',
            name='obser_0',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='obser_1',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='obser_2',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='obser_3',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='obser_4',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='obser_5',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='obser_6',
            field=models.CharField(blank=True, choices=[('Foo Bar', 'Foo Bar'), ('Anthony Ackerman', 'Anthony Ackerman'), ('Kerra Janis', 'Kerra Janis'), ('Tristian Licht', 'Tristian Licht'), ('Micah Trierweiler', 'Micah Trierweiler'), ('Tobias Ackerman', 'Tobias Ackerman'), ('Alyssa Kersanty', 'Alyssa Kersanty')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='paved',
            field=models.CharField(choices=[('p1', '#4 Booster Station'), ('p2', '#5 Battery Road'), ('p3', 'Coal Dump Horseshoe'), ('p4', 'Coal Handling Road (Partial)'), ('p5', 'Coke Plant Road'), ('p6', 'Coke Plant Mech Road'), ('p7', 'North Gate Area'), ('p8', 'Compund Road'), ('p9', 'D-4 Blast Furnace Road'), ('p10', 'Gap Gate Road'), ('p11', '#3 Ore Dock Road'), ('p12', 'River Road'), ('p13', 'Weigh Station Road'), ('p14', 'Zug Island Road')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 51, 16, 91132)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 51, 16, 91145)),
        ),
    ]
