# Generated by Django 3.2.4 on 2021-08-02 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0160_auto_20210802_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='formM_readings_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pav_1', models.CharField(max_length=30)),
                ('pav_2', models.CharField(max_length=30)),
                ('pav_3', models.CharField(max_length=30)),
                ('pav_4', models.CharField(max_length=30)),
                ('pav_5', models.CharField(max_length=30)),
                ('pav_6', models.CharField(max_length=30)),
                ('pav_7', models.CharField(max_length=30)),
                ('pav_8', models.CharField(max_length=30)),
                ('pav_9', models.CharField(max_length=30)),
                ('pav_10', models.CharField(max_length=30)),
                ('pav_11', models.CharField(max_length=30)),
                ('pav_12', models.CharField(max_length=30)),
                ('unp_1', models.CharField(max_length=30)),
                ('unp_2', models.CharField(max_length=30)),
                ('unp_3', models.CharField(max_length=30)),
                ('unp_4', models.CharField(max_length=30)),
                ('unp_5', models.CharField(max_length=30)),
                ('unp_6', models.CharField(max_length=30)),
                ('unp_7', models.CharField(max_length=30)),
                ('unp_8', models.CharField(max_length=30)),
                ('unp_9', models.CharField(max_length=30)),
                ('unp_10', models.CharField(max_length=30)),
                ('unp_11', models.CharField(max_length=30)),
                ('unp_12', models.CharField(max_length=30)),
                ('par_1', models.CharField(max_length=30)),
                ('par_2', models.CharField(max_length=30)),
                ('par_3', models.CharField(max_length=30)),
                ('par_4', models.CharField(max_length=30)),
                ('par_5', models.CharField(max_length=30)),
                ('par_6', models.CharField(max_length=30)),
                ('par_7', models.CharField(max_length=30)),
                ('par_8', models.CharField(max_length=30)),
                ('par_9', models.CharField(max_length=30)),
                ('par_10', models.CharField(max_length=30)),
                ('par_11', models.CharField(max_length=30)),
                ('par_12', models.CharField(max_length=30)),
                ('storage_1', models.CharField(max_length=30)),
                ('storage_2', models.CharField(max_length=30)),
                ('storage_3', models.CharField(max_length=30)),
                ('storage_4', models.CharField(max_length=30)),
                ('storage_5', models.CharField(max_length=30)),
                ('storage_6', models.CharField(max_length=30)),
                ('storage_7', models.CharField(max_length=30)),
                ('storage_8', models.CharField(max_length=30)),
                ('storage_9', models.CharField(max_length=30)),
                ('storage_10', models.CharField(max_length=30)),
                ('storage_11', models.CharField(max_length=30)),
                ('storage_12', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 14, 23, 5, 995106)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 14, 23, 5, 995119)),
        ),
    ]
