# Generated by Django 3.2.4 on 2021-08-02 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0161_auto_20210802_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='formm_readings_model',
            name='par_total',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formm_readings_model',
            name='pav_total',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formm_readings_model',
            name='storage_total',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formm_readings_model',
            name='unp_total',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 14, 43, 37, 748386)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 14, 43, 37, 748400)),
        ),
    ]
