# Generated by Django 3.2.4 on 2021-08-02 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0170_auto_20210802_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='formm_readings_model',
            name='form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.formm_model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 15, 24, 55, 602648)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 15, 24, 55, 602662)),
        ),
    ]
