# Generated by Django 3.2.4 on 2021-08-02 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0171_auto_20210802_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='formm_readings_model',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.formm_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 15, 26, 0, 541428)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 15, 26, 0, 541441)),
        ),
    ]
