# Generated by Django 3.2.4 on 2021-08-03 01:00

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0173_auto_20210802_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formc_model',
            name='area_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='area_stop_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='truck_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='truck_stop_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 21, 0, 37, 494362)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 21, 0, 37, 494375)),
        ),
        
    ]
