# Generated by Django 3.2.4 on 2021-08-03 01:09

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0174_auto_20210802_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 21, 9, 3, 762173)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 21, 9, 3, 762186)),
        ),
        
    ]
