# Generated by Django 3.2.4 on 2021-08-04 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0179_auto_20210802_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma5_model',
            name='ambient_temp_start',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='forma5_model',
            name='wind_speed_start',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 0, 2, 35, 845196)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 0, 2, 35, 845209)),
        ),
    ]
