# Generated by Django 3.2.4 on 2021-08-05 01:01

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0180_auto_20210804_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile_model',
            name='position',
            field=models.CharField(default='Technician', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 21, 0, 58, 555916)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 21, 0, 58, 555930)),
        ),
    ]
