# Generated by Django 3.2.6 on 2021-08-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0134_auto_20210727_1934'),
        ('EES_Forms', '0189_auto_20210808_0019'),
    ]

    operations = [
    ]
