# Generated by Django 3.2.4 on 2021-08-19 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0190_auto_20210818_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='spill_kits_model',
            name='month',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 21, 37, 29, 988196)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 21, 37, 29, 988210)),
        ),
    ]
