# Generated by Django 3.2.7 on 2023-02-02 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bat_info_model',
            old_name='County',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bat_info_model',
            old_name='emission_point',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='bat_info_model',
            old_name='op_mode1',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_average_1',
            new_name='PEC_average_a',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_average_2',
            new_name='PEC_average_b',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_average_3',
            new_name='PEC_average_c',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_average_m',
            new_name='PEC_average_main',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_oven_1',
            new_name='PEC_oven_a',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_oven_2',
            new_name='PEC_oven_b',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_oven_3',
            new_name='PEC_oven_c',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_1',
            new_name='PEC_read_a_1',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_10',
            new_name='PEC_read_a_2',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_11',
            new_name='PEC_read_a_3',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_12',
            new_name='PEC_read_a_4',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_13',
            new_name='PEC_read_a_5',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_14',
            new_name='PEC_read_a_6',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_15',
            new_name='PEC_read_a_7',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_16',
            new_name='PEC_read_a_8',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_17',
            new_name='PEC_read_b_1',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_18',
            new_name='PEC_read_b_2',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_19',
            new_name='PEC_read_b_3',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_2',
            new_name='PEC_read_b_4',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_20',
            new_name='PEC_read_b_5',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_21',
            new_name='PEC_read_b_6',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_22',
            new_name='PEC_read_b_7',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_23',
            new_name='PEC_read_b_8',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_24',
            new_name='PEC_read_c_1',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_3',
            new_name='PEC_read_c_2',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_4',
            new_name='PEC_read_c_3',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_5',
            new_name='PEC_read_c_4',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_6',
            new_name='PEC_read_c_5',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_7',
            new_name='PEC_read_c_6',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_8',
            new_name='PEC_read_c_7',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_read_9',
            new_name='PEC_read_c_8',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_start_1',
            new_name='PEC_start_a',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_start_2',
            new_name='PEC_start_b',
        ),
        migrations.RenameField(
            model_name='formg2_readings_model',
            old_name='PEC_start_3',
            new_name='PEC_start_c',
        ),
        migrations.RemoveField(
            model_name='bat_info_model',
            name='op_mode2',
        ),
        migrations.RemoveField(
            model_name='bat_info_model',
            name='process_equip1',
        ),
        migrations.RemoveField(
            model_name='bat_info_model',
            name='process_equip2',
        ),
        migrations.RemoveField(
            model_name='forma5_model',
            name='canvasMediaFile',
        ),
        migrations.AddField(
            model_name='bat_info_model',
            name='bat_height_label',
            field=models.CharField(choices=[('ft', 'Feet'), ('m', 'Meters')], default=45, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bat_info_model',
            name='bat_lids',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bat_info_model',
            name='bat_main',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='facility',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='forma1_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forma2_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forma3_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forma4_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forma5_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formb_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formc_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formd_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forme_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formg1_model',
            name='canvas',
            field=models.CharField(default='-', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg1_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formg1_readings_model',
            name='PEC_oven1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='formg1_readings_model',
            name='PEC_oven2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='formg1_readings_model',
            name='PEC_time1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formg1_readings_model',
            name='PEC_time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formg1_readings_model',
            name='PEC_type',
            field=models.CharField(default='-', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_model',
            name='canvas',
            field=models.CharField(default='-', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formh_model',
            name='canvas',
            field=models.CharField(default='-', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_formL',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_29',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_30',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_31',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_32',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_33',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_34',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_35',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_36',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_37',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_38',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_39',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_40',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_41',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_42',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_43',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_44',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_45',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_46',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_47',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_48',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_49',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_50',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_51',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_52',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_53',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_54',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_55',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_56',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_57',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_58',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_59',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_60',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formi_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forml_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formm_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formo_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='formp_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forms',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='issues_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='issues_model',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spill_kits_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='user_profile_model',
            name='certs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_profile_model',
            name='company',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='estab_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='total_ovens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='inop_ovens',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='forma1_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c1_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c2_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c3_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c4_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c5_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='comments',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forma3_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='notes',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='forma5_model',
            name='notes',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='comments',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_emissions_present',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formh_readings_model',
            name='comb_read_25',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formh_readings_model',
            name='comb_read_26',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formh_readings_model',
            name='comb_read_27',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formh_readings_model',
            name='comb_read_28',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='m_comments_0',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='m_comments_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='m_comments_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='m_comments_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='m_comments_4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='m_comments_5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='m_comments_6',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='v_comments_0',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='v_comments_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='v_comments_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='v_comments_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='v_comments_4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='v_comments_5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forml_model',
            name='v_comments_6',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='paved',
            field=models.CharField(choices=[('p1', '#4 Booster Station'), ('p2', '#5 Battery Road'), ('p3', 'Coal Dump Horseshoe'), ('p4', 'Coal Handling Road (Partial)'), ('p5', 'Coke Plant Road'), ('p6', 'Coke Plant Mech Road'), ('p7', 'North Gate Area'), ('p8', 'Compund Road'), ('p9', 'Gap Gate Road'), ('p10', '#3 Ore Dock Road'), ('p11', 'River Road'), ('p12', 'Weigh Station Road'), ('p13', 'Zug Island Road')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='unpaved',
            field=models.CharField(choices=[('unp1', 'North Gate Truck Turn'), ('unp2', 'Screening Station Road'), ('unp3', 'Coal Handling Road (Partial)'), ('unp4', 'Taj Mahal Road'), ('unp5', 'PECS Approach'), ('unp6', 'No. 2 Boilerhouse Road'), ('unp7', 'D-4 Blast Furnace Road'), ('unp8', 'Bypass Route')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forms',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly '), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 16, 48, 9, 775370)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 16, 48, 9, 775469)),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='observer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk10_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk10_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk10_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk10_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk10_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk11_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk11_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk11_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk11_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk11_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk12_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk12_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk12_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk12_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk12_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk13_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk13_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk13_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk13_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk13_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk14_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk14_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk14_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk14_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk14_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk15_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk15_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk15_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk15_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk15_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk16_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk16_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk16_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk16_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk16_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk17_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk17_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk17_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk17_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk17_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk18_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk18_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk18_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk18_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk18_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk19_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk19_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk19_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk19_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk19_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk1_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk1_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk1_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk1_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk1_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk20_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk20_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk20_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk20_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk20_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk21_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk21_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk21_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk21_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk21_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk2_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk2_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk2_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk2_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk2_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk3_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk3_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk3_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk3_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk3_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk4_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk4_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk4_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk4_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk4_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk5_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk5_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk5_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk5_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk5_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk6_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk6_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk6_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk6_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk6_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk7_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk7_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk7_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk7_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk7_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk8_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk8_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk8_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk8_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk8_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk9_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk9_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk9_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk9_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='sk9_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut23_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut23_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut23_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut23_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut23_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut24_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut24_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut24_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut24_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut24_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut25_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut25_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut25_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut25_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut25_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut26_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut26_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut26_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut26_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut26_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut27_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut27_complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut27_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut27_serial',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='spill_kits_model',
            name='skut27_tag_on',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='cert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='phone',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='position',
            field=models.CharField(choices=[('SGI Technician', 'SGI Technician'), ('SGI Admin', 'SGI Admin'), ('EES Coke Employees', 'EES Coke Employees')], max_length=75),
        ),
        migrations.CreateModel(
            name='signature_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=30)),
                ('sign_date', models.DateField(blank=True)),
                ('canvas', models.CharField(max_length=100000)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
            ],
        ),
        migrations.CreateModel(
            name='quarterly_trucks_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=4)),
                ('date', models.DateField()),
                ('observer_5_1', models.CharField(blank=True, max_length=30, null=True)),
                ('date_5_1', models.DateField(blank=True, null=True)),
                ('time_5_1', models.TimeField(blank=True, null=True)),
                ('comments_5_1', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_5_1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_5_1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_5_1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_5_1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('observer_6_2', models.CharField(blank=True, max_length=30, null=True)),
                ('date_6_2', models.DateField(blank=True, null=True)),
                ('time_6_2', models.TimeField(blank=True, null=True)),
                ('comments_6_2', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_6_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_6_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_6_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_6_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('observer_7_3', models.CharField(blank=True, max_length=30, null=True)),
                ('date_7_3', models.DateField(blank=True, null=True)),
                ('time_7_3', models.TimeField(blank=True, null=True)),
                ('comments_7_3', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_7_3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_7_3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_7_3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_7_3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('observer_9_4', models.CharField(blank=True, max_length=30, null=True)),
                ('date_9_4', models.DateField(blank=True, null=True)),
                ('time_9_4', models.TimeField(blank=True, null=True)),
                ('comments_9_4', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_9_4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_9_4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_9_4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_9_4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
            ],
        ),
    ]
