# Generated by Django 4.2.9 on 2024-08-13 03:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_settings_model',
            name='subChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.formsubmissionrecords_model'),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='is_battery',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='braintreeplans',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 23, 21, 3, 145960)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 23, 21, 3, 145979)),
        ),
    ]
