# Generated by Django 4.2.9 on 2024-07-30 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat_info_model',
            name='dashboard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bat_info_model',
            name='is_battery',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='forme_model',
            name='goose_neck_data',
            field=models.CharField(default={}, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 0, 35, 32, 843941)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 0, 35, 32, 843957)),
        ),
        migrations.CreateModel(
            name='packets_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('formList', models.JSONField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly '), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], default='Weekly', max_length=30)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
            ],
        ),
        migrations.CreateModel(
            name='form_settings_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
                ('facilityChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
                ('formChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.forms')),
                ('packetChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.packets_model')),
            ],
        ),
    ]
