# Generated by Django 4.2.9 on 2024-10-07 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0002_form7_model_area_json_1_form7_model_area_json_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form7_model',
            name='area_sel',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='area_start_time',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='area_stop_time',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='average_p',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='average_salt',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='average_storage',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='average_t',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='salt_start_time',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='salt_stop_time',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='sto_start_time',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='sto_stop_time',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='truck_sel',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='truck_start_time',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='truck_stop_time',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 1, 56, 52, 968089)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 1, 56, 52, 968101)),
        ),
    ]
