# Generated by Django 4.2.9 on 2024-08-18 23:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0002_form_settings_model_subchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma1_model',
            name='formSettingsChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.form_settings_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 19, 58, 7, 683620)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 19, 58, 7, 683633)),
        ),
    ]
