# Generated by Django 3.2.7 on 2023-10-29 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0003_auto_20231029_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_battery_profile_model',
            name='facility',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 15, 59, 52, 388162)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 15, 59, 52, 388174)),
        ),
    ]
