# Generated by Django 3.2.7 on 2022-09-09 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0003_auto_20220909_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma3_model',
            name='one_pass',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 15, 25, 35, 740568)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 15, 25, 35, 740585)),
        ),
    ]
