# Generated by Django 3.2.7 on 2023-10-28 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0003_auto_20231028_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='facility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 13, 54, 4, 325178)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 13, 54, 4, 325192)),
        ),
    ]
