# Generated by Django 4.2.9 on 2024-08-28 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0003_forma1_model_formsettingschoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues_model',
            name='out_of_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 22, 7, 45, 917310)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 22, 7, 45, 917323)),
        ),
        migrations.AlterField(
            model_name='the_packets_model',
            name='formList',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
