# Generated by Django 3.2.4 on 2021-08-24 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0003_auto_20210822_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma2_model',
            name='c_leak_loc1',
        ),
        migrations.RemoveField(
            model_name='forma2_model',
            name='c_leak_oven1',
        ),
        migrations.RemoveField(
            model_name='forma2_model',
            name='c_leak_zone1',
        ),
        migrations.RemoveField(
            model_name='forma2_model',
            name='p_leak_loc1',
        ),
        migrations.RemoveField(
            model_name='forma2_model',
            name='p_leak_oven1',
        ),
        migrations.RemoveField(
            model_name='forma2_model',
            name='p_leak_zone1',
        ),
        migrations.AddField(
            model_name='forma2_model',
            name='c_leak_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='forma2_model',
            name='p_leak_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 21, 24, 1, 420639)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 21, 24, 1, 420656)),
        ),
    ]
