# Generated by Django 4.2.9 on 2024-10-13 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0003_remove_form7_model_area_sel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form22_model',
            name='paved',
            field=models.CharField(choices=[('p1', '#4 Booster Station'), ('p2', '#5 Battery Road'), ('p3', 'Coal Dump Horseshoe'), ('p4', 'Coal Handling Road (Partial)'), ('p5', 'Coke Plant Road'), ('p6', 'Coke Plant Mech Road'), ('p7', 'North Gate Area'), ('p8', 'Compound Road'), ('p9', 'Gap Gate Road'), ('p10', '#3 Ore Dock Road'), ('p11', 'River Road'), ('p12', 'Weigh Station Road'), ('p13', 'Zug Island Road')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 17, 25, 54, 920760)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 17, 25, 54, 920772)),
        ),
    ]
