# Generated by Django 4.2.9 on 2024-10-19 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0004_alter_form22_model_paved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat_info_model',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 23, 58, 0, 476082)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 23, 58, 0, 476097)),
        ),
    ]
