# Generated by Django 3.2.7 on 2023-10-28 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0004_auto_20231028_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_battery_profile_model',
            name='facility',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 13, 56, 45, 23747)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 13, 56, 45, 23761)),
        ),
    ]
