# Generated by Django 3.2.7 on 2022-09-10 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0004_auto_20220909_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma5_model',
            name='canvasMediaFile',
            field=models.FileField(default='/images/A-5scetchBlack.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_emissions_present',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 19, 56, 36, 378589)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 19, 56, 36, 378606)),
        ),
    ]
