# Generated by Django 3.2.7 on 2021-09-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0002_auto_20210831_1020'),
        ('EES_Forms', '0004_auto_20210823_2124'),
    ]

    operations = [
    ]
