# Generated by Django 3.2.7 on 2023-10-29 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0004_auto_20231029_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sop_model',
            old_name='pdf_link',
            new_name='pdf_url',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 16, 51, 26, 783931)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 16, 51, 26, 783948)),
        ),
        migrations.AlterField(
            model_name='sop_model',
            name='pdf_file',
            field=models.FileField(upload_to='media/SOPs/'),
        ),
    ]
