# Generated by Django 3.2.7 on 2022-09-19 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0005_auto_20220910_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formm_model',
            name='unpaved',
            field=models.CharField(choices=[('unp1', 'North Gate Truck Turn'), ('unp2', 'Screening Station Road'), ('unp3', 'Coal Handling Road (Partial)'), ('unp4', 'Taj Mahal Road'), ('unp5', 'PECS Approach'), ('unp6', 'No. 2 Boilerhouse Road'), ('unp7', 'Bypass Route')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 19, 24, 36, 554229)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 19, 24, 36, 554247)),
        ),
    ]
