# Generated by Django 3.2.7 on 2023-10-29 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0005_auto_20231029_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 17, 21, 56, 98668)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 17, 21, 56, 98683)),
        ),
        migrations.AlterField(
            model_name='sop_model',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
