# Generated by Django 4.2.9 on 2024-09-07 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0006_form17_model_form18_model_form19_model_form22_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 15, 23, 1, 550349)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 15, 23, 1, 550361)),
        ),
        migrations.CreateModel(
            name='form8_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('observer1', models.CharField(blank=True, max_length=30, null=True)),
                ('truck_id1', models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor'), ('Security', 'Security'), ('Water Truck', 'Water Truck')], max_length=30, null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('time1', models.TimeField(blank=True, null=True)),
                ('contents1', models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True)),
                ('freeboard1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('wetted1', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('comments1', models.CharField(blank=True, max_length=30, null=True)),
                ('observer2', models.CharField(blank=True, max_length=30, null=True)),
                ('truck_id2', models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor'), ('Security', 'Security'), ('Water Truck', 'Water Truck')], max_length=30, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('time2', models.TimeField(blank=True, null=True)),
                ('contents2', models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True)),
                ('freeboard2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('wetted2', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('comments2', models.CharField(blank=True, max_length=30, null=True)),
                ('observer3', models.CharField(blank=True, max_length=30, null=True)),
                ('truck_id3', models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor'), ('Security', 'Security'), ('Water Truck', 'Water Truck')], max_length=30, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('time3', models.TimeField(blank=True, null=True)),
                ('contents3', models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True)),
                ('freeboard3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('wetted3', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('comments3', models.CharField(blank=True, max_length=30, null=True)),
                ('observer4', models.CharField(blank=True, max_length=30, null=True)),
                ('truck_id4', models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor'), ('Security', 'Security'), ('Water Truck', 'Water Truck')], max_length=30, null=True)),
                ('date4', models.DateField(blank=True, null=True)),
                ('time4', models.TimeField(blank=True, null=True)),
                ('contents4', models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True)),
                ('freeboard4', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('wetted4', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('comments4', models.CharField(blank=True, max_length=30, null=True)),
                ('observer5', models.CharField(blank=True, max_length=30, null=True)),
                ('truck_id5', models.CharField(blank=True, choices=[('#5', '#5'), ('#6', '#6'), ('#7', '#7'), ('#9', '#9'), ('Dozer', 'Dozer'), ('Semi', 'Semi'), ('Contractor', 'Contractor'), ('Security', 'Security'), ('Water Truck', 'Water Truck')], max_length=30, null=True)),
                ('date5', models.DateField(blank=True, null=True)),
                ('time5', models.TimeField(blank=True, null=True)),
                ('contents5', models.CharField(blank=True, choices=[('Coal', 'Coal'), ('Coke', 'Coke'), ('Breeze', 'Breeze')], max_length=30, null=True)),
                ('freeboard5', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('wetted5', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('comments5', models.CharField(blank=True, max_length=30, null=True)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
            ],
        ),
    ]
