# Generated by Django 3.2.7 on 2023-11-01 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0006_auto_20231029_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='colorMode',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode')], default='light', max_length=5),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 5, 47, 36, 102348)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 5, 47, 36, 102361)),
        ),
        migrations.AlterField(
            model_name='sop_model',
            name='pdf_file',
            field=models.FileField(upload_to='SOPs/'),
        ),
        migrations.AlterField(
            model_name='sop_model',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
