# Generated by Django 4.2.9 on 2024-10-21 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0006_sop_model_facilitychoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_packets_model',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 15, 2, 18, 902619)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 15, 2, 18, 902634)),
        ),
    ]
