# Generated by Django 3.2.7 on 2022-09-19 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0006_auto_20220919_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formh_readings_model',
            name='comb_read_25',
        ),
        migrations.RemoveField(
            model_name='formh_readings_model',
            name='comb_read_26',
        ),
        migrations.RemoveField(
            model_name='formh_readings_model',
            name='comb_read_27',
        ),
        migrations.RemoveField(
            model_name='formh_readings_model',
            name='comb_read_28',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 19, 42, 9, 461543)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 19, 42, 9, 461563)),
        ),
    ]
