# Generated by Django 4.2.9 on 2024-11-08 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0007_remove_the_packets_model_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintree_model',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 11, 17, 4, 537413)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 11, 17, 4, 537426)),
        ),
    ]
