# Generated by Django 3.2.7 on 2023-11-01 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0007_auto_20231101_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 8, 35, 9, 117048)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 8, 35, 9, 117061)),
        ),
        migrations.CreateModel(
            name='notifications_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('hovered', models.BooleanField(default=False)),
                ('header', models.CharField(choices=[('compliance', 'OUT OF COMPLIANCE'), ('90days', '90 DAY OVENS'), ('message', 'NEW MESSAGE'), ('event', 'NEW EVENT'), ('schedule', 'SCHEDULE UPDATED'), ('dark', 'Dark Mode')], max_length=50)),
                ('body', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('facilityChoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.user_profile_model')),
            ],
        ),
    ]
