# Generated by Django 4.2.9 on 2024-09-08 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0008_alter_forma1_readings_model_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 0, 33, 41, 249250)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 0, 33, 41, 249261)),
        ),
    ]
