# Generated by Django 3.2.7 on 2022-09-26 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0008_auto_20220923_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c1_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c2_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c3_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c4_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='c5_comments',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='forma1_readings_model',
            name='comments',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='notes',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='forma5_model',
            name='notes',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='comments',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 17, 25, 29, 352917)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 17, 25, 29, 352934)),
        ),
    ]
