# Generated by Django 3.2.7 on 2023-11-03 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0008_auto_20231101_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications_model',
            name='formData',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications_model',
            name='header',
            field=models.CharField(choices=[('compliance', 'OUT OF COMPLIANCE'), ('90days', '90 DAY OVENS'), ('message', 'MESSAGE'), ('event', 'EVENT'), ('schedule', 'SCHEDULE UPDATED'), ('submitted', 'FORM SUBMITTED'), ('corrective', 'CORRECTIVE ACTION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 20, 56, 58, 692589)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 20, 56, 58, 692603)),
        ),
    ]
