# Generated by Django 4.2.9 on 2024-11-12 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0008_braintree_model_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braintree_model',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='payment_method_token',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='planID',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='planName',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='price',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='registrations',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='braintree_model',
            name='subID',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 9, 19, 26, 9, 443045)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 19, 26, 9, 443061)),
        ),
    ]
