# Generated by Django 3.2.7 on 2023-11-03 21:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0009_auto_20231102_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications_model',
            name='date',
        ),
        migrations.AddField(
            model_name='notifications_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 17, 25, 7, 862219)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 17, 25, 7, 862233)),
        ),
    ]
