# Generated by Django 3.2.7 on 2021-10-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0010_auto_20211003_0729'),
        ('EES_Forms', '0010_auto_20211003_1943'),
    ]

    operations = [
    ]
