# Generated by Django 4.2.9 on 2024-09-11 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0010_bat_info_model_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 19, 15, 59, 142674)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 19, 15, 59, 142689)),
        ),
    ]
