# Generated by Django 3.2.7 on 2022-09-27 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0010_auto_20220927_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues_model',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 14, 39, 30, 797753)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 14, 39, 30, 797770)),
        ),
    ]
