# Generated by Django 3.2.7 on 2021-10-08 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0011_merge_0010_auto_20211003_0729_0010_auto_20211003_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 20, 39, 47, 799665)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 20, 39, 47, 799682)),
        ),
    ]
