# Generated by Django 3.2.7 on 2022-11-12 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0011_auto_20220927_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma1_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forma3_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 17, 11, 25, 697681)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 17, 11, 25, 697703)),
        ),
    ]
