# Generated by Django 3.2.7 on 2021-10-08 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0012_auto_20211007_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 22, 34, 48, 427630)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 22, 34, 48, 427648)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='position',
            field=models.CharField(choices=[('SGI Technician', 'SGI Technician'), ('SGI Admin', 'SGI Admin'), ('SGI Quality Control', 'SGI Quality Control'), ('EES Coke Personnel', 'EES Coke Personnel')], max_length=75),
        ),
    ]
