# Generated by Django 4.2.9 on 2025-01-26 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0012_form5_model_ovens_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form5_model',
            name='reading_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 1, 15, 9, 383424)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 1, 15, 9, 383436)),
        ),
    ]
