# Generated by Django 4.2.9 on 2024-10-05 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0012_remove_forma1_readings_model_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='the_packets_model',
            old_name='formList',
            new_name='settings',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 20, 43, 21, 224023)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 20, 43, 21, 224038)),
        ),
    ]
