<<<<<<< Updated upstream
# Generated by Django 3.2.7 on 2021-10-21 10:58
=======
# Generated by Django 3.2.7 on 2021-10-08 19:50
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0012_auto_20211007_2039'),
        ('EES_Forms', '0013_auto_20211007_2234'),
    ]

    operations = [
    ]
