# Generated by Django 4.2.9 on 2025-01-30 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0013_form5_model_reading_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form5_model',
            name='formSettings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.form_settings_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 21, 59, 41, 43066)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 21, 59, 41, 43083)),
        ),
    ]
