# Generated by Django 3.2.7 on 2021-10-08 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0014_merge_0012_auto_20211007_2039_0013_auto_20211007_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 15, 50, 46, 704369)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 15, 50, 46, 704387)),
        ),
    ]
