# Generated by Django 3.2.7 on 2021-10-21 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0014_merge_0012_auto_20211007_2039_0013_auto_20211007_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 6, 58, 46, 497206)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 6, 58, 46, 497221)),
        ),
    ]
