# Generated by Django 4.2.9 on 2025-02-14 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0014_form5_model_formsettings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='from26_model',
            new_name='form29_model',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 21, 35, 8, 838542)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 21, 35, 8, 838557)),
        ),
        migrations.DeleteModel(
            name='spill_kits_model',
        ),
    ]
