# Generated by Django 4.2.9 on 2025-02-17 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0015_rename_from26_model_form29_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form5_model',
            name='ambient_temp_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='ambient_temp_stop',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='background_color_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='background_color_stop',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='describe_background_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='describe_background_stop',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='describe_emissions_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='describe_emissions_stop',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='direction_from',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='distance_from',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='emission_color_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='emission_color_stop',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='emission_point_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='emission_point_stop',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='height_above_ground',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='height_rel_observer',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='op_mode1',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='op_mode2',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='plume_opacity_determined_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='plume_opacity_determined_stop',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='plume_type',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='process_equip1',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='process_equip2',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='sky_conditions',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='water_drolet_present',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='water_droplet_plume',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='wind_speed_start',
        ),
        migrations.RemoveField(
            model_name='form5_model',
            name='wind_speed_stop',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 16, 52, 44, 453278)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 16, 52, 44, 453293)),
        ),
    ]
