# Generated by Django 3.2.7 on 2023-11-14 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0015_auto_20231113_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='active',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 21, 8, 52, 813190)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 8, 52, 813204)),
        ),
    ]
