# Generated by Django 3.2.7 on 2022-12-20 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0015_auto_20221220_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='formg1_readings_model',
            name='PEC_type',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 18, 43, 37, 902799)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 18, 43, 37, 902816)),
        ),
    ]
