# Generated by Django 4.2.9 on 2025-02-20 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0016_remove_form5_model_ambient_temp_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1_model',
            name='ovens_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 0, 2, 57, 598147)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 0, 2, 57, 598169)),
        ),
    ]
