# Generated by Django 3.2.7 on 2023-11-14 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0016_auto_20231113_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 21, 9, 29, 987732)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 9, 29, 987747)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='active',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
