# Generated by Django 3.2.7 on 2022-04-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0015_auto_20211021_0658'),
        ('EES_Forms', '0016_auto_20211101_1507'),
    ]

    operations = [
    ]
