# Generated by Django 3.2.7 on 2022-04-01 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0017_merge_0015_auto_20211021_0658_0016_auto_20211101_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 20, 55, 27, 16165)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 20, 55, 27, 16187)),
        ),
    ]
