# Generated by Django 3.2.7 on 2022-12-21 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0017_auto_20221220_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_25',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_26',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_27',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_28',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_29',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_30',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_31',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_32',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_33',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_34',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_35',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_36',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_37',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_38',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_39',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_40',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_41',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_42',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_43',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_44',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_45',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_46',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_47',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_48',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_49',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_50',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_51',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_52',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_53',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_54',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_55',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_56',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_57',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_58',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_59',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_read_60',
            field=models.CharField(default='0', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 16, 56, 51, 607059)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 16, 56, 51, 607078)),
        ),
    ]
