# Generated by Django 3.2.7 on 2023-11-14 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0017_auto_20231113_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 21, 11, 50, 345747)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 11, 50, 345761)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
