# Generated by Django 4.2.9 on 2025-02-20 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0017_form1_model_ovens_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1_model',
            name='formSettings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.form_settings_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 16, 44, 38, 479927)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 16, 44, 38, 479941)),
        ),
    ]
