# Generated by Django 4.2.9 on 2025-02-21 03:11

import EES_Forms.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0018_form1_model_formsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1_model',
            name='formSettings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='EES_Forms.form_settings_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 22, 11, 45, 19919)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 22, 11, 45, 19933)),
        ),
        migrations.AlterField(
            model_name='sop_model',
            name='pdf_file',
            field=models.FileField(upload_to=EES_Forms.models.sop_file_upload_path),
        ),
        migrations.AlterField(
            model_name='sop_model',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
