# Generated by Django 3.2.7 on 2022-12-22 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0018_auto_20221221_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma5_model',
            name='canvasMediaFile',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 13, 49, 45, 907446)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 13, 49, 45, 907465)),
        ),
    ]
