# Generated by Django 3.2.7 on 2022-12-22 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0019_auto_20221222_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='formg1_model',
            name='canvas',
            field=models.CharField(default='-', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_model',
            name='canvas',
            field=models.CharField(default='-', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_model',
            name='canvas',
            field=models.CharField(default='-', max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 16, 3, 5, 807692)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 16, 3, 5, 807710)),
        ),
    ]
