# Generated by Django 3.2.7 on 2022-04-01 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0019_auto_20220331_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma3_model',
            name='inop_numbs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 3, 56, 966823)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 22, 3, 56, 966847)),
        ),
    ]
