# Generated by Django 3.2.7 on 2023-11-30 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EES_Forms', '0019_auto_20231129_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 2, 21, 17, 547312)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 2, 21, 17, 547326)),
        ),
        migrations.CreateModel(
            name='braintree_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('customerID', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_method_token', models.CharField(blank=True, max_length=500, null=True)),
                ('subID', models.CharField(blank=True, max_length=500, null=True)),
                ('planID', models.CharField(max_length=150)),
                ('planName', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('registrations', models.IntegerField()),
                ('next_billing_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company_model',
            name='braintree',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.braintree_model'),
        ),
    ]
