# Generated by Django 4.2.9 on 2025-02-21 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0019_alter_form1_model_formsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 22, 25, 3, 807275)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 22, 25, 3, 807290)),
        ),
        migrations.AlterField(
            model_name='sop_model',
            name='pdf_file',
            field=models.FileField(upload_to='SOPs/'),
        ),
    ]
