# Generated by Django 3.2.7 on 2022-04-01 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0020_auto_20220331_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma3_model',
            name='l_oven1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='forma3_model',
            name='om_oven1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 23, 12, 47, 382387)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 23, 12, 47, 382408)),
        ),
    ]
