# Generated by Django 3.2.7 on 2023-11-30 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0021_auto_20231130_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braintree_model',
            name='price',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 3, 45, 19, 488267)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 3, 45, 19, 488284)),
        ),
    ]
