# Generated by Django 4.2.9 on 2025-02-26 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0021_issues_model_userchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='submitted',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 14, 41, 48, 897526)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 14, 41, 48, 897538)),
        ),
    ]
