# Generated by Django 4.2.9 on 2025-02-26 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0022_remove_forms_date_submitted_remove_forms_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues_model',
            name='form',
        ),
        migrations.AddField(
            model_name='issues_model',
            name='formChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.forms'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 14, 55, 7, 634622)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 14, 55, 7, 634635)),
        ),
    ]
