# Generated by Django 3.2.7 on 2023-12-02 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0022_auto_20231130_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bat_info_model',
            name='formsList',
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_height_label',
            field=models.CharField(blank=True, choices=[('ft', 'Feet'), ('m', 'Meters')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_lids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_main',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='county',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='equip_location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='estab_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='total_ovens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 3, 3, 26, 905964)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 3, 3, 26, 905977)),
        ),
    ]
