# Generated by Django 3.2.7 on 2022-12-22 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0022_auto_20221222_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_formL',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 17, 54, 22, 975633)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 17, 54, 22, 975655)),
        ),
    ]
