# Generated by Django 3.2.7 on 2022-04-01 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0022_auto_20220331_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma3_model',
            old_name='l_loc1',
            new_name='l_leaks2',
        ),
        migrations.RenameField(
            model_name='forma3_model',
            old_name='om_loc1',
            new_name='om_leaks2',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 2, 7, 56, 674769)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 2, 7, 56, 674796)),
        ),
    ]
