# Generated by Django 4.2.9 on 2025-02-26 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0023_remove_issues_model_form_issues_model_formchoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues_model',
            name='formChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.form_settings_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 15, 7, 22, 11628)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 15, 7, 22, 11641)),
        ),
    ]
