# Generated by Django 3.2.7 on 2023-12-08 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0023_auto_20231202_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='observer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 15, 22, 11, 131304)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 15, 22, 11, 131320)),
        ),
    ]
