# Generated by Django 3.2.7 on 2022-04-01 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0023_auto_20220401_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma3_model',
            name='l_leaks2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forma3_model',
            name='om_leaks2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 2, 34, 19, 638982)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 2, 34, 19, 639001)),
        ),
    ]
