# Generated by Django 3.2.7 on 2022-12-23 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0024_auto_20221222_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 16, 22, 56, 467421)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 16, 22, 56, 467439)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='cert_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
