# Generated by Django 4.2.9 on 2025-02-27 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0025_form17_model_formsettings_form18_model_formsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 22, 34, 37, 293251)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 22, 34, 37, 293267)),
        ),
        migrations.CreateModel(
            name='form30_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('area_name', models.CharField(max_length=100)),
                ('inspection_json', models.JSONField(blank=True, default=dict, null=True)),
                ('containers_json', models.JSONField(blank=True, default=dict, null=True)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
                ('formSettings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.form_settings_model')),
            ],
        ),
    ]
