# Generated by Django 3.2.7 on 2022-12-23 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0025_auto_20221223_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 16, 39, 27, 28173)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 16, 39, 27, 28191)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='position',
            field=models.CharField(choices=[('SGI Technician', 'SGI Technician'), ('SGI Admin', 'SGI Admin'), ('EES Coke Personnel', 'EES Coke Employees')], max_length=75),
        ),
    ]
