# Generated by Django 3.2.7 on 2024-01-02 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0026_auto_20240101_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_model',
            name='active',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 23, 9, 8, 509420)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 23, 9, 8, 509432)),
        ),
    ]
