# Generated by Django 4.2.9 on 2025-03-10 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0026_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 19, 33, 4, 970223)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 19, 33, 4, 970238)),
        ),
        migrations.CreateModel(
            name='form31_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer', models.CharField(max_length=255, verbose_name='Inspector Name')),
                ('date', models.DateField(verbose_name='Inspection Date')),
                ('time', models.TimeField(verbose_name='Inspection Time')),
                ('tank_json', models.JSONField(default=dict, verbose_name='Tank Data')),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
                ('formSettings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.form_settings_model')),
            ],
        ),
    ]
