# Generated by Django 3.2.7 on 2022-12-24 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0026_auto_20221223_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='quarterly_trucks_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('observer_5_1', models.CharField(blank=True, max_length=30, null=True)),
                ('date_5_1', models.DateField(blank=True, null=True)),
                ('time_5_1', models.TimeField(blank=True, null=True)),
                ('comments_5_1', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_5_1', models.BooleanField(default=False)),
                ('box_interior_5_1', models.BooleanField(default=False)),
                ('box_exterior_5_1', models.BooleanField(default=False)),
                ('exhaust_5_1', models.BooleanField(default=False)),
                ('observer_6_2', models.CharField(blank=True, max_length=30, null=True)),
                ('date_6_2', models.DateField(blank=True, null=True)),
                ('time_6_2', models.TimeField(blank=True, null=True)),
                ('comments_6_2', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_6_2', models.BooleanField(default=False)),
                ('box_interior_6_2', models.BooleanField(default=False)),
                ('box_exterior_6_2', models.BooleanField(default=False)),
                ('exhaust_6_2', models.BooleanField(default=False)),
                ('observer_7_3', models.CharField(blank=True, max_length=30, null=True)),
                ('date_7_3', models.DateField(blank=True, null=True)),
                ('time_7_3', models.TimeField(blank=True, null=True)),
                ('comments_7_3', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_7_3', models.BooleanField(default=False)),
                ('box_interior_7_3', models.BooleanField(default=False)),
                ('box_exterior_7_3', models.BooleanField(default=False)),
                ('exhaust_7_3', models.BooleanField(default=False)),
                ('observer_9_4', models.CharField(blank=True, max_length=30, null=True)),
                ('date_9_4', models.DateField(blank=True, null=True)),
                ('time_9_4', models.TimeField(blank=True, null=True)),
                ('comments_9_4', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_9_4', models.BooleanField(default=False)),
                ('box_interior_9_4', models.BooleanField(default=False)),
                ('box_exterior_9_4', models.BooleanField(default=False)),
                ('exhaust_9_4', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 16, 49, 5, 777549)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 16, 49, 5, 777568)),
        ),
    ]
