# Generated by Django 3.2.7 on 2022-04-02 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0026_auto_20220401_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma5_model',
            name='canvas',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 22, 21, 31, 871421)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 22, 21, 31, 871439)),
        ),
    ]
