# Generated by Django 3.2.7 on 2022-04-02 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0027_auto_20220401_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='inop_numbs',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 15, 20, 48, 25164)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 15, 20, 48, 25184)),
        ),
    ]
