# Generated by Django 3.2.7 on 2022-12-24 22:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0027_auto_20221224_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterly_trucks_model',
            name='year',
        ),
        migrations.AddField(
            model_name='quarterly_trucks_model',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 17, 22, 56, 595839)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 17, 22, 56, 595856)),
        ),
    ]
