# Generated by Django 3.2.7 on 2024-01-02 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0027_auto_20240101_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_model',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='company_model',
            name='payment_method_token',
        ),
        migrations.RemoveField(
            model_name='company_model',
            name='subID',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 23, 19, 52, 521000)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 23, 19, 52, 521013)),
        ),
    ]
