# Generated by Django 3.2.7 on 2022-04-02 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0028_auto_20220402_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma2_model',
            name='inop_numbs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 16, 53, 34, 358422)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 16, 53, 34, 358441)),
        ),
    ]
