# Generated by Django 3.2.7 on 2022-12-24 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0028_auto_20221224_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 17, 46, 50, 67831)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 17, 46, 50, 67849)),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='quarter',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=4),
        ),
    ]
