# Generated by Django 3.2.7 on 2024-01-08 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0028_auto_20240101_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 18, 45, 42, 943529)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 18, 45, 42, 943546)),
        ),
    ]
