# Generated by Django 3.2.7 on 2022-12-24 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0030_auto_20221224_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 18, 49, 9, 254613)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 18, 49, 9, 254634)),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_exterior_5_1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_exterior_6_2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_exterior_7_3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_exterior_9_4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_interior_5_1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_interior_6_2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_interior_7_3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='box_interior_9_4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='exhaust_5_1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='exhaust_6_2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='exhaust_7_3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='exhaust_9_4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='rear_gate_5_1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='rear_gate_6_2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='rear_gate_7_3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quarterly_trucks_model',
            name='rear_gate_9_4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
    ]
