# Generated by Django 3.2.7 on 2022-04-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0028_auto_20220402_1455'),
        ('EES_Forms', '0031_auto_20220402_1657'),
    ]

    operations = [
    ]
