# Generated by Django 4.2.9 on 2025-04-03 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0031_remove_form1_model_facilitychoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form5_readings_model',
            name='form',
        ),
        migrations.RemoveField(
            model_name='form7_readings_model',
            name='form',
        ),
        migrations.RemoveField(
            model_name='form6_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form7_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form8_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form9_model',
            name='facilityChoice',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 2, 17, 52, 42, 258724)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 17, 52, 42, 258736)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.form5_model'),
        ),
        migrations.DeleteModel(
            name='form1_readings_model',
        ),
        migrations.DeleteModel(
            name='form5_readings_model',
        ),
        migrations.DeleteModel(
            name='form7_readings_model',
        ),
    ]
