# Generated by Django 4.2.9 on 2025-04-04 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0032_remove_form5_readings_model_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form18_readings_model',
            name='form',
        ),
        migrations.RemoveField(
            model_name='form19_readings_model',
            name='form',
        ),
        migrations.RemoveField(
            model_name='form17_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form18_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form19_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form21_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form22_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form26_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form27_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form29_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form30_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='form31_model',
            name='facilityChoice',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 3, 14, 19, 7, 884184)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 14, 19, 7, 884195)),
        ),
        migrations.DeleteModel(
            name='form17_readings_model',
        ),
        migrations.DeleteModel(
            name='form18_readings_model',
        ),
        migrations.DeleteModel(
            name='form19_readings_model',
        ),
    ]
