# Generated by Django 3.2.7 on 2022-04-06 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0032_merge_0028_auto_20220402_1455_0031_auto_20220402_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma3_model',
            name='inop_numbs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 9, 58, 19, 357409)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 9, 58, 19, 357422)),
        ),
    ]
