# Generated by Django 3.2.7 on 2022-04-27 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0032_merge_0028_auto_20220402_1455_0031_auto_20220402_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma3_model',
            name='inop_numbs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 21, 40, 31, 463871)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 21, 40, 31, 463888)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='position',
            field=models.CharField(choices=[('SGI Technician', 'SGI Technician'), ('SGI Admin', 'SGI Admin'), ('SGI Quality Control', 'SGI Quality Control'), ('EES Coke Personnel', 'EES Coke Employees')], max_length=75),
        ),
    ]
