# Generated by Django 3.2.7 on 2022-12-28 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0032_auto_20221224_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='inop_ovens',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 15, 54, 25, 41838)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 15, 54, 25, 41855)),
        ),
    ]
