# Generated by Django 3.2.7 on 2022-12-29 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0033_auto_20221228_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bat_info_model',
            old_name='emission_point',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='bat_info_model',
            old_name='op_mode1',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='bat_info_model',
            name='op_mode2',
        ),
        migrations.RemoveField(
            model_name='bat_info_model',
            name='process_equip1',
        ),
        migrations.RemoveField(
            model_name='bat_info_model',
            name='process_equip2',
        ),
        migrations.AddField(
            model_name='bat_info_model',
            name='bat_height_label',
            field=models.CharField(default='feet', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bat_info_model',
            name='bat_lids',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bat_info_model',
            name='bat_main',
            field=models.CharField(default='single', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 14, 13, 48, 935855)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 14, 13, 48, 935872)),
        ),
    ]
