# Generated by Django 4.2.9 on 2025-04-10 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0033_remove_form18_readings_model_form_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bat_info_model',
            new_name='facility_model',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 0, 51, 59, 55730)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 0, 51, 59, 55745)),
        ),
    ]
