# Generated by Django 4.2.9 on 2025-04-10 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0034_rename_bat_info_model_facility_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_model',
            name='facilityForms',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility', to='EES_Forms.facility_forms_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 15, 34, 4, 61361)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 15, 34, 4, 61374)),
        ),
    ]
