# Generated by Django 4.2.9 on 2024-01-13 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0034_auto_20240111_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='facility_tags_register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=70, null=True)),
                ('contents', models.CharField(max_length=40)),
                ('construction_date', models.DateField(blank=True, null=True)),
                ('last_repair_reconstruction', models.DateField(blank=True, null=True)),
                ('height', models.CharField(max_length=20)),
                ('diameter', models.CharField(max_length=20)),
                ('capacity', models.CharField(max_length=20)),
                ('last_change_service_date', models.DateField(blank=True, null=True)),
                ('construction', models.CharField(max_length=200)),
                ('design', models.CharField(max_length=40)),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('rectangular', 'Rectangular')], max_length=40)),
                ('containment', models.CharField(max_length=40)),
                ('CRDM', models.CharField(blank=True, max_length=200, null=True)),
                ('release_prevention_barrier', models.CharField(blank=True, max_length=200, null=True)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
            ],
        ),
        migrations.AddField(
            model_name='settings_model',
            name='units_measurements',
            field=models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='imperial', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 3, 46, 57, 187438)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 3, 46, 57, 187450)),
        ),
        migrations.CreateModel(
            name='form28_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('retain_until_date', models.DateField()),
                ('prior_inspection_date', models.DateField()),
                ('containment_structure', models.CharField(max_length=100)),
                ('primary_tank', models.CharField(max_length=100)),
                ('cont_drain_valves', models.CharField(max_length=100)),
                ('pathways_entry', models.CharField(max_length=100)),
                ('tank_leaks', models.CharField(max_length=100)),
                ('secondary_cont_leaks', models.CharField(max_length=100)),
                ('interstice_leaks', models.CharField(max_length=100)),
                ('valves', models.CharField(max_length=200)),
                ('spill_cont_boxes', models.CharField(max_length=200)),
                ('liquid_level_equipment', models.CharField(max_length=200)),
                ('overfill_equipment', models.CharField(max_length=200)),
                ('piping_connections', models.CharField(max_length=100)),
                ('ladder_platform_structure', models.CharField(max_length=100)),
                ('other_conditions', models.CharField(max_length=200)),
                ('additional_comments', models.CharField(max_length=200)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
                ('tankChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.facility_tags_register_model')),
            ],
        ),
    ]
