# Generated by Django 4.2.9 on 2024-01-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0035_facility_tags_register_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='facility_tags_register_model',
            name='tankID',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 45, 56, 287379)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 15, 45, 56, 287391)),
        ),
    ]
