# Generated by Django 4.2.9 on 2024-01-13 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0036_faq_model_facility_tags_register_model_tankid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_model',
            name='section',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 16, 34, 28, 502961)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 16, 34, 28, 502973)),
        ),
    ]
