# Generated by Django 3.2.7 on 2022-12-29 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0036_auto_20221229_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bat_info_model',
            name='city',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 14, 58, 50, 813140)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 14, 58, 50, 813158)),
        ),
    ]
