# Generated by Django 4.2.9 on 2024-01-14 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0037_faq_model_section_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_model',
            name='link',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings_model',
            name='dashboard_template',
            field=models.CharField(choices=[('Default', 'Default'), ('Coke Battery Dashboard', 'Coke Battery Dashboard')], default='Default', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq_model',
            name='answer',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 4, 36, 526048)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 12, 4, 36, 526061)),
        ),
    ]
