# Generated by Django 4.2.9 on 2024-01-18 00:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EES_Forms', '0038_faq_model_link_settings_model_dashboard_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 19, 46, 18444)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 19, 19, 46, 18460)),
        ),
        migrations.CreateModel(
            name='form_requests_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('how_data_is_collected', models.CharField(max_length=700)),
                ('inspection_of', models.CharField(max_length=150)),
                ('form_example_file', models.FileField(upload_to='formRequests/')),
                ('form_example_url', models.CharField(blank=True, max_length=1000000)),
                ('optimize', models.BooleanField(default=False)),
                ('detailed_description', models.CharField(max_length=1000)),
                ('callBack_days', models.CharField(choices=[('Everyday', 'Everyday'), ('0', 'Mondays'), ('1', 'Tuesdays'), ('2', 'Wednesdays'), ('3', 'Thursdays'), ('4', 'Fridays'), ('5', 'Saturdays'), ('6', 'Sundays'), ('Weekends', 'Weekends'), ('Weekdays', 'Weekdays')], max_length=30)),
                ('callBack_time', models.TimeField()),
                ('callBack_time_freq', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=15)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly '), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
