# Generated by Django 4.2.9 on 2025-04-15 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0038_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='subscriptionID',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 2, 0, 0, 453373)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 2, 0, 0, 453386)),
        ),
    ]
