# Generated by Django 3.2.7 on 2022-12-29 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0038_auto_20221229_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 15, 29, 55, 412029)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 15, 29, 55, 412049)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='position',
            field=models.CharField(choices=[('SGI Technician', 'SGI Technician'), ('SGI Admin', 'SGI Admin'), ('EES Coke Employees', 'EES Coke Employees')], max_length=75),
        ),
    ]
