# Generated by Django 4.2.9 on 2024-01-18 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0039_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_model',
            name='link',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='form_requests_model',
            name='callBack_days',
            field=models.CharField(choices=[('', 'Days Available'), ('Everyday', 'Everyday'), ('0', 'Mondays'), ('1', 'Tuesdays'), ('2', 'Wednesdays'), ('3', 'Thursdays'), ('4', 'Fridays'), ('5', 'Saturdays'), ('6', 'Sundays'), ('Weekends', 'Weekends'), ('Weekdays', 'Weekdays')], max_length=30),
        ),
        migrations.AlterField(
            model_name='form_requests_model',
            name='optimize',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 2, 22, 45, 774098)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 2, 22, 45, 774114)),
        ),
    ]
