# Generated by Django 3.2.7 on 2022-12-29 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0039_auto_20221229_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bat_info_model',
            old_name='County',
            new_name='county',
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_height_label',
            field=models.CharField(choices=[('ft', 'Feet'), ('m', 'Meters')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 16, 2, 14, 626713)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 16, 2, 14, 626733)),
        ),
    ]
