# Generated by Django 3.2.7 on 2022-12-29 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0040_auto_20221229_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_lids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_main',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='bat_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='estab_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bat_info_model',
            name='total_ovens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 16, 22, 30, 266387)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 16, 22, 30, 266406)),
        ),
    ]
