# Generated by Django 3.2.7 on 2022-07-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0033_auto_20220426_2140'),
        ('EES_Forms', '0041_auto_20220522_1839'),
    ]

    operations = [
    ]
