# Generated by Django 3.2.7 on 2022-12-29 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0041_auto_20221229_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='facility',
            field=models.CharField(default='EES Coke Battery', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 17, 44, 48, 375881)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 17, 44, 48, 375900)),
        ),
    ]
