# Generated by Django 4.2.9 on 2025-04-18 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0041_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications_model',
            name='formSettings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.form_settings_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 15, 57, 52, 954342)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 15, 57, 52, 954355)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='companyChoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='EES_Forms.company_model'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EES_Forms.braintreeplans'),
        ),
    ]
