# Generated by Django 3.2.7 on 2022-07-05 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0042_merge_0033_auto_20220426_2140_0041_auto_20220522_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 14, 23, 32, 405248)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 14, 23, 32, 405265)),
        ),
    ]
