# Generated by Django 3.2.7 on 2022-12-30 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0042_auto_20221229_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='signature_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=30)),
                ('sign_date', models.DateField(blank=True)),
                ('canvas', models.CharField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 1, 12, 0, 704392)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 1, 12, 0, 704410)),
        ),
    ]
