# Generated by Django 4.2.9 on 2024-02-13 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0042_alter_packets_model_formlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packets_model',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly '), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 21, 26, 21, 40099)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 21, 26, 21, 40111)),
        ),
    ]
