# Generated by Django 3.2.7 on 2023-01-02 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0043_auto_20221230_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='facility',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 23, 37, 20, 316011)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 23, 37, 20, 316029)),
        ),
    ]
