# Generated by Django 4.2.9 on 2025-05-02 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0043_event_allday_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 11, 6, 57, 107670)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 11, 6, 57, 107681)),
        ),
    ]
