# Generated by Django 3.2.7 on 2022-07-10 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0044_auto_20220708_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='day_freq',
            field=models.CharField(choices=[('Everyday', 'Everyday'), ('0', 'Mondays'), ('1', 'Tuesdays'), ('2', 'Wednesdays'), ('3', 'Thursdays'), ('4', 'Fridays'), ('5', 'Saturdays'), ('6', 'Sundays'), ('Weekends', 'Weekends'), ('Weekdays', 'Weekdays')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 2, 18, 47, 188013)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 2, 18, 47, 188033)),
        ),
    ]
