# Generated by Django 3.2.7 on 2023-01-02 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0044_auto_20230101_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma1_model',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 15, 27, 6, 429936)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 15, 27, 6, 429955)),
        ),
    ]
