# Generated by Django 4.2.9 on 2025-05-07 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0045_alter_notifications_model_formdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_model',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons'),
        ),
        migrations.AlterField(
            model_name='notifications_model',
            name='header',
            field=models.CharField(choices=[('compliance', 'OUT OF COMPLIANCE'), ('90days', '90 DAY OVENS'), ('message', 'MESSAGE'), ('event', 'EVENT'), ('schedule', 'SCHEDULE UPDATED'), ('submitted', 'FORM SUBMITTED'), ('deviations', 'CORRECTIVE ACTION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 0, 40, 41, 162879)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 0, 40, 41, 162894)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
