# Generated by Django 3.2.7 on 2023-01-02 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0045_auto_20230102_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma1_model',
            old_name='facility',
            new_name='facilityChoice',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 15, 37, 51, 195375)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 15, 37, 51, 195395)),
        ),
    ]
