# Generated by Django 4.2.9 on 2024-03-02 01:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0046_alter_packets_model_formlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 20, 51, 38, 68364)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 20, 51, 38, 68377)),
        ),
        migrations.CreateModel(
            name='form_settings_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(default='default')),
                ('facilityChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
                ('formChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.forms')),
            ],
        ),
    ]
