# Generated by Django 3.2.7 on 2023-01-03 00:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0046_auto_20230102_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma2_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forma3_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forma4_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AddField(
            model_name='forma5_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 19, 4, 27, 660901)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 19, 4, 27, 660918)),
        ),
    ]
