# Generated by Django 3.2.7 on 2022-07-12 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0047_auto_20220711_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formc_model',
            name='average_p',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='average_t',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 18, 48, 31, 361023)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 18, 48, 31, 361042)),
        ),
    ]
