# Generated by Django 4.2.9 on 2024-03-02 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0047_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_settings_model',
            name='settings',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 20, 52, 38, 601762)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 20, 52, 38, 601781)),
        ),
    ]
