# Generated by Django 3.2.7 on 2022-07-13 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0048_auto_20220712_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formm_model',
            name='sto_start',
        ),
        migrations.RemoveField(
            model_name='formm_model',
            name='sto_stop',
        ),
        migrations.RemoveField(
            model_name='formm_model',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_1',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_10',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_11',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_12',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_2',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_3',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_4',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_5',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_6',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_7',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_8',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_9',
        ),
        migrations.RemoveField(
            model_name='formm_readings_model',
            name='storage_total',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 20, 23, 22, 556006)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 20, 23, 22, 556023)),
        ),
    ]
