# Generated by Django 4.2.9 on 2024-03-02 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0048_alter_form_settings_model_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_settings_model',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 20, 53, 16, 941317)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 20, 53, 16, 941330)),
        ),
    ]
