# Generated by Django 4.2.9 on 2024-03-08 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0049_alter_form_settings_model_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_settings_model',
            name='packetChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.packets_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 12, 7, 4, 778494)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 12, 7, 4, 778513)),
        ),
    ]
