# Generated by Django 3.2.7 on 2022-07-13 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0049_auto_20220712_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='sop_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('revision_date', models.DateField(blank=True)),
                ('pdf_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 48, 32, 488577)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 15, 48, 32, 488595)),
        ),
    ]
