# Generated by Django 4.2.9 on 2025-05-17 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0049_remove_event_enteredby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='personal',
        ),
        migrations.AddField(
            model_name='event',
            name='alerts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='calendarChoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 16, 42, 41, 47571)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 16, 42, 41, 47586)),
        ),
    ]
