# Generated by Django 4.2.9 on 2024-03-08 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0050_form_settings_model_packetchoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_settings_model',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 12, 11, 22, 651496)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 12, 11, 22, 651518)),
        ),
    ]
