# Generated by Django 4.2.9 on 2025-05-19 04:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0050_remove_event_personal_event_alerts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmissionrecords_model',
            name='facilityChoice',
        ),
        migrations.RemoveField(
            model_name='formsubmissionrecords_model',
            name='formID',
        ),
        migrations.AlterField(
            model_name='facility_forms_model',
            name='facilityChoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_forms', to='EES_Forms.facility_model'),
        ),
        migrations.AlterField(
            model_name='form_settings_model',
            name='subChoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_settings', to='EES_Forms.formsubmissionrecords_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 0, 25, 44, 40053)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 0, 25, 44, 40066)),
        ),
    ]
