# Generated by Django 4.2.9 on 2025-05-19 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0051_remove_formsubmissionrecords_model_facilitychoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_settings_model',
            name='packetChoice',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 0, 27, 41, 418632)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 0, 27, 41, 418646)),
        ),
    ]
