# Generated by Django 3.2.7 on 2023-01-09 04:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0052_auto_20230103_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 23, 56, 12, 409460)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 23, 56, 12, 409478)),
        ),
    ]
