# Generated by Django 4.2.9 on 2025-05-19 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0052_remove_form_settings_model_packetchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility_model',
            name='facilityForms',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 1, 30, 56, 427433)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 1, 30, 56, 427452)),
        ),
    ]
