# Generated by Django 4.2.9 on 2024-03-09 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0052_bat_info_model_is_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat_info_model',
            name='dashboard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 19, 22, 45, 647929)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 19, 22, 45, 647946)),
        ),
    ]
