# Generated by Django 4.2.9 on 2025-05-19 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0053_remove_facility_model_facilityforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 1, 35, 27, 678299)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 1, 35, 27, 678318)),
        ),
        migrations.DeleteModel(
            name='facility_forms_model',
        ),
    ]
