# Generated by Django 4.2.9 on 2025-05-22 04:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0055_form29_model_data_alter_pt_admin1_model_add_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 0, 14, 14, 363786)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 0, 14, 14, 363798)),
        ),
        migrations.CreateModel(
            name='SpillKit_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('tag_on', models.BooleanField(default=False)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('report', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spill_kits', to='EES_Forms.form29_model')),
            ],
        ),
    ]
