# Generated by Django 3.2.7 on 2023-01-12 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0055_auto_20230111_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 22, 2, 47, 33984)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 22, 2, 47, 34006)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics'),
        ),
    ]
