# Generated by Django 3.2.7 on 2022-07-19 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0055_auto_20220718_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_model',
            name='pdf_file',
            field=models.FileField(default='sop.pdf', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 21, 30, 36, 720142)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 21, 30, 36, 720160)),
        ),
    ]
