# Generated by Django 3.2.7 on 2023-01-15 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0057_auto_20230114_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='certs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 23, 33, 36, 370347)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 33, 36, 370370)),
        ),
    ]
