# Generated by Django 3.2.7 on 2023-01-15 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0058_auto_20230114_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 1, 11, 31, 727125)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 1, 11, 31, 727146)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='phone',
            field=models.CharField(max_length=75),
        ),
    ]
