# Generated by Django 4.2.9 on 2025-05-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0058_remove_form29_model_sk10_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pt_admin1_model',
        ),
    ]
