# Generated by Django 3.2.7 on 2025-06-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0059_delete_pt_admin1_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='form20_model',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendarChoice',
            field=models.CharField(blank=True, default='Personal', max_length=50, null=True),
        ),
    ]
