# Generated by Django 3.2.7 on 2025-06-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0060_auto_20250620_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form20_model',
            name='obser_0',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='obser_1',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='obser_2',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='obser_3',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='obser_4',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='time_0',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='time_1',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='time_2',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='time_3',
        ),
        migrations.RemoveField(
            model_name='form20_model',
            name='time_4',
        ),
    ]
