# Generated by Django 3.2.7 on 2025-06-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0061_auto_20250620_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form24_model',
            name='weekend_day',
            field=models.CharField(blank=True, choices=[('5', 'Saturday'), ('6', 'Sunday')], max_length=30, null=True),
        ),
    ]
