# Generated by Django 3.2.7 on 2023-02-06 03:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0061_auto_20230201_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='paved',
            field=models.CharField(choices=[('p1', '#4 Booster Station'), ('p2', '#5 Battery Road'), ('p3', 'Coal Dump Horseshoe'), ('p4', 'Coal Handling Road (Partial)'), ('p5', 'Coke Plant Road'), ('p6', 'Coke Plant Mech Road'), ('p7', 'North Gate Area'), ('p8', 'Compund Road'), ('p9', 'Gap Gate Road'), ('p10', '#3 Ore Dock Road'), ('p11', 'River Road'), ('p12', 'Weigh Station Road'), ('p13', 'Zug Island Road')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formm_model',
            name='unpaved',
            field=models.CharField(choices=[('unp1', 'North Gate Truck Turn'), ('unp2', 'Screening Station Road'), ('unp3', 'Coal Handling Road (Partial)'), ('unp4', 'Taj Mahal Road'), ('unp5', 'PECS Approach'), ('unp6', 'No. 2 Boilerhouse Road'), ('unp7', 'D-4 Blast Furnace Road'), ('unp8', 'Bypass Route')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 22, 31, 44, 589339)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 22, 31, 44, 589355)),
        ),
    ]
