# Generated by Django 3.2.7 on 2023-02-06 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0062_auto_20230205_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 16, 3, 9, 614484)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 16, 3, 9, 614501)),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='position',
            field=models.CharField(choices=[('observer', 'Observer'), ('supervisor', 'Supervisor'), ('client', 'Client')], max_length=75),
        ),
    ]
