# Generated by Django 3.2.7 on 2025-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0062_alter_form24_model_weekend_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_1',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_2',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_3',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_4',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_5',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_6',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_7',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_8',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='Q_9',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='actions_taken',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='month',
        ),
        migrations.RemoveField(
            model_name='form24_model',
            name='weekend_day',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_1',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_2',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_3',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_4',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_5',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_6',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_7',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_8',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='Q_9',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='actions_taken',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='month',
        ),
        migrations.RemoveField(
            model_name='form25_model',
            name='weekend_day',
        ),
        migrations.AddField(
            model_name='form24_model',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='form25_model',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
