# Generated by Django 3.2.7 on 2022-07-30 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0063_auto_20220729_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formc_model',
            name='salt_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='salt_stop_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='sto_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formc_model',
            name='sto_stop_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 20, 50, 33, 122186)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 20, 50, 33, 122205)),
        ),
    ]
