# Generated by Django 3.2.7 on 2023-02-06 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0063_auto_20230206_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma4_model',
            name='leak_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 17, 39, 22, 871840)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 17, 39, 22, 871858)),
        ),
    ]
