# Generated by Django 3.2.7 on 2022-08-22 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0064_auto_20220729_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Rice', 'Rice')], max_length=10),
        ),
        migrations.AlterField(
            model_name='forma1_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Rice', 'Rice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forma2_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Rice', 'Rice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forma3_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Rice', 'Rice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forma4_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Rice', 'Rice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forme_model',
            name='foreman',
            field=models.CharField(choices=[('Zajas', 'Zajas'), ('Folding', 'Folding'), ('Cooper', 'Cooper'), ('Rice', 'Rice')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 23, 38, 46, 546617)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 23, 38, 46, 546634)),
        ),
    ]
