# Generated by Django 3.2.7 on 2022-08-22 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0065_auto_20220821_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_battery_profile_model',
            name='foreman',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 19, 10, 24, 263842)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 19, 10, 24, 263859)),
        ),
    ]
