# Generated by Django 3.2.7 on 2023-02-07 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0065_auto_20230206_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma4_model',
            name='comp_by_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='date_comp_repair_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='date_init_repair_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='date_temp_seal_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='oven_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='temp_seal_by_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='time_comp_repair_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='time_init_repair_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='time_leak_1',
        ),
        migrations.RemoveField(
            model_name='forma4_model',
            name='time_temp_seal_leak_1',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 22, 58, 23, 923130)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 22, 58, 23, 923148)),
        ),
    ]
