# Generated by Django 3.2.7 on 2025-07-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0065_articlefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2_model',
            name='c_leak_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='form2_model',
            name='p_leak_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
