# Generated by Django 3.2.7 on 2025-07-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0066_auto_20250723_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2_model',
            name='c_temp_block_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='form2_model',
            name='c_temp_block_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='form2_model',
            name='p_temp_block_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='form2_model',
            name='p_temp_block_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
