# Generated by Django 3.2.7 on 2022-08-23 01:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0067_auto_20220822_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_average',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formh_readings_model',
            name='comb_stop',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 21, 20, 58, 622118)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 21, 20, 58, 622135)),
        ),
    ]
