# Generated by Django 3.2.7 on 2025-07-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0067_auto_20250724_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form3_model',
            name='l_leak_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='form3_model',
            name='l_leaks2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form3_model',
            name='om_leak_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='form3_model',
            name='om_leaks2',
            field=models.IntegerField(default=0),
        ),
    ]
