# Generated by Django 3.2.7 on 2022-08-23 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0068_auto_20220822_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formh_model',
            name='cert_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 21, 55, 14, 733782)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 21, 55, 14, 733800)),
        ),
    ]
