# Generated by Django 3.2.7 on 2025-08-10 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EES_Forms', '0068_auto_20250726_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSettingsRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('change_type', models.CharField(default='update', max_length=20)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='EES_Forms.form_settings_model')),
            ],
            options={
                'ordering': ['-revision_date', '-id'],
            },
        ),
    ]
