# Generated by Django 3.2.7 on 2023-02-16 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0069_auto_20230216_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_model',
            name='city',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_model',
            name='state',
            field=models.CharField(default='na', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_model',
            name='zipcode',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_model',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='company_model',
            name='company_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='company_model',
            name='phone',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 14, 24, 9, 426514)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 14, 24, 9, 426532)),
        ),
    ]
