# Generated by Django 3.2.7 on 2022-09-02 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0070_auto_20220822_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 16, 17, 31, 35351)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 16, 17, 31, 35370)),
        ),
        migrations.CreateModel(
            name='formG_readings_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PEC_read_1', models.CharField(max_length=3)),
                ('PEC_read_2', models.CharField(max_length=3)),
                ('PEC_read_3', models.CharField(max_length=3)),
                ('PEC_read_4', models.CharField(max_length=3)),
                ('PEC_read_5', models.CharField(max_length=3)),
                ('PEC_read_6', models.CharField(max_length=3)),
                ('PEC_read_7', models.CharField(max_length=3)),
                ('PEC_read_8', models.CharField(max_length=3)),
                ('PEC_read_9', models.CharField(max_length=3)),
                ('PEC_read_10', models.CharField(max_length=3)),
                ('PEC_read_11', models.CharField(max_length=3)),
                ('PEC_read_12', models.CharField(max_length=3)),
                ('PEC_read_13', models.CharField(max_length=3)),
                ('PEC_read_14', models.CharField(max_length=3)),
                ('PEC_read_15', models.CharField(max_length=3)),
                ('PEC_read_16', models.CharField(max_length=3)),
                ('PEC_read_17', models.CharField(max_length=3)),
                ('PEC_read_18', models.CharField(max_length=3)),
                ('PEC_read_19', models.CharField(max_length=3)),
                ('PEC_read_20', models.CharField(max_length=3)),
                ('PEC_read_21', models.CharField(max_length=3)),
                ('PEC_read_22', models.CharField(max_length=3)),
                ('PEC_read_23', models.CharField(max_length=3)),
                ('PEC_read_24', models.CharField(max_length=3)),
                ('PEC_read_25', models.CharField(max_length=3)),
                ('PEC_read_26', models.CharField(max_length=3)),
                ('PEC_read_27', models.CharField(max_length=3)),
                ('PEC_read_28', models.CharField(max_length=3)),
                ('PEC_start', models.TimeField()),
                ('PEC_stop', models.TimeField()),
                ('PEC_average', models.FloatField(blank=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.formg1_model')),
            ],
        ),
    ]
