# Generated by Django 3.2.7 on 2022-09-02 21:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0071_auto_20220902_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='formg_readings_model',
            name='PEC_emissions_present',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='formg_readings_model',
            name='PEC_observe_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg_readings_model',
            name='PEC_push_oven',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg_readings_model',
            name='PEC_push_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 10, 41, 17995)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 17, 10, 41, 18012)),
        ),
    ]
