# Generated by Django 3.2.7 on 2023-02-16 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0072_auto_20230216_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat_info_model',
            name='formsList',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 15, 28, 36, 154164)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 15, 28, 36, 154183)),
        ),
    ]
