# Generated by Django 3.2.7 on 2022-09-02 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0072_auto_20220902_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formg_readings_model',
            name='PEC_push_oven',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 11, 43, 945935)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 17, 11, 43, 945953)),
        ),
    ]
