# Generated by Django 3.2.7 on 2022-09-03 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0073_auto_20220902_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formG_readings_model',
            new_name='formG1_readings_model',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 20, 43, 48, 363903)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 20, 43, 48, 363920)),
        ),
    ]
