# Generated by Django 3.2.7 on 2023-02-23 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0075_auto_20230222_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_model',
            name='customerID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 22, 41, 26, 950766)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 22, 41, 26, 950783)),
        ),
    ]
