# Generated by Django 3.2.7 on 2022-09-03 01:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0075_auto_20220902_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formg1_readings_model',
            name='PEC_read_25',
        ),
        migrations.RemoveField(
            model_name='formg1_readings_model',
            name='PEC_read_26',
        ),
        migrations.RemoveField(
            model_name='formg1_readings_model',
            name='PEC_read_27',
        ),
        migrations.RemoveField(
            model_name='formg1_readings_model',
            name='PEC_read_28',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_average',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_emissions_present',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_observe_time',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_push_oven',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_push_time',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_read_25',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_read_26',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_read_27',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_read_28',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_start',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='PEC_stop',
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_average_1',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_average_2',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_average_3',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_average_m',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_oven_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_oven_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_oven_3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_start_1',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_start_2',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formg2_readings_model',
            name='PEC_start_3',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 21, 19, 37, 564232)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 21, 19, 37, 564249)),
        ),
    ]
