# Generated by Django 3.2.7 on 2022-09-03 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0076_auto_20220902_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formg1_model',
            name='cert_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formg1_model',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formg2_model',
            name='cert_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formg2_model',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='formh_model',
            name='ambient_temp_start',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='formh_model',
            name='wind_speed_start',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 22, 17, 18, 495575)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 22, 17, 18, 495593)),
        ),
    ]
