# Generated by Django 3.2.7 on 2022-09-03 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0077_auto_20220902_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formg1_model',
            name='ambient_temp_start',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='formg1_model',
            name='wind_speed_start',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_emissions_present',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_observe_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_push_oven',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_push_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_10',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_11',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_12',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_13',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_14',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_15',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_16',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_17',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_18',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_19',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_20',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_21',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_22',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_23',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_24',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_4',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_5',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_6',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_7',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_8',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_read_9',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_stop',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formg2_model',
            name='ambient_temp_start',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='formg2_model',
            name='wind_speed_start',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='formh_model',
            name='ambient_temp_start',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='formh_model',
            name='wind_speed_start',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 23, 23, 30, 141720)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 23, 23, 30, 141737)),
        ),
    ]
