# Generated by Django 3.2.7 on 2023-02-28 03:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0078_auto_20230227_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formselect',
            name='facilityChoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 22, 43, 22, 864812)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 22, 43, 22, 864830)),
        ),
    ]
