# Generated by Django 3.2.7 on 2022-09-03 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0078_auto_20220902_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_emissions_present',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_observe_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_push_oven',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='PEC_push_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 23, 24, 51, 288947)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 23, 24, 51, 288964)),
        ),
    ]
