# Generated by Django 3.2.7 on 2023-02-28 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0079_auto_20230227_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formSelect',
            new_name='facility_forms_model',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 22, 47, 42, 759648)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 22, 47, 42, 759669)),
        ),
    ]
