# Generated by Django 3.2.7 on 2023-08-27 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0080_auto_20230227_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 16, 48, 12, 623287)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 16, 48, 12, 623302)),
        ),
        migrations.CreateModel(
            name='spill_kit_inventory_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inspector', models.CharField(max_length=40)),
                ('skID', models.IntegerField()),
                ('type', models.CharField(choices=[('oil XL cart', 'PIG Spill Kit in Extra-Large Response Chest'), ('universal drum', 'PIG Spill Kit in Overpack Salvage Drum')], max_length=50)),
                ('counted_items', models.IntegerField()),
                ('missing_items', models.IntegerField()),
                ('spill_kit_submitted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.spill_kits_model')),
            ],
        ),
    ]
