# Generated by Django 3.2.7 on 2022-09-03 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0081_auto_20220902_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formg1_readings_model',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formg2_readings_model',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formh_readings_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='formg1_readings_model',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.formg1_model'),
        ),
        migrations.AlterField(
            model_name='formg2_readings_model',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.formg2_model'),
        ),
        migrations.AlterField(
            model_name='formh_readings_model',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.formh_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 23, 40, 3, 317532)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 23, 40, 3, 317549)),
        ),
    ]
