# Generated by Django 3.2.7 on 2022-09-06 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0086_auto_20220906_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma3_model',
            name='one_pass',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 14, 38, 40, 62254)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 14, 38, 40, 62272)),
        ),
    ]
