# Generated by Django 3.2.7 on 2022-09-06 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0088_auto_20220906_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma3_model',
            name='one_pass',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 15, 20, 16, 343454)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 15, 20, 16, 343474)),
        ),
    ]
