# Generated by Django 3.2.7 on 2023-08-27 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0088_auto_20230827_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spill_kits_model',
            old_name='skut27_comment',
            new_name='skut22_comment',
        ),
        migrations.RenameField(
            model_name='spill_kits_model',
            old_name='skut27_complete',
            new_name='skut22_complete',
        ),
        migrations.RenameField(
            model_name='spill_kits_model',
            old_name='skut27_report',
            new_name='skut22_report',
        ),
        migrations.RenameField(
            model_name='spill_kits_model',
            old_name='skut27_serial',
            new_name='skut22_serial',
        ),
        migrations.RenameField(
            model_name='spill_kits_model',
            old_name='skut27_tag_on',
            new_name='skut22_tag_on',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 19, 8, 58, 210028)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 19, 8, 58, 210042)),
        ),
    ]
