# Generated by Django 3.2.7 on 2022-09-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0071_auto_20220902_1441'),
        ('EES_Forms', '0090_auto_20220907_2223'),
    ]

    operations = [
    ]
