# Generated by Django 3.2.7 on 2023-10-04 05:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0092_auto_20230901_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 1, 24, 41, 7996)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 1, 24, 41, 8010)),
        ),
        migrations.CreateModel(
            name='formSubmissionRecords_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formID', models.IntegerField()),
                ('dateSubmitted', models.DateField()),
                ('dueDate', models.DateField()),
                ('submitted', models.BooleanField(default=False)),
                ('facilityChoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
            ],
        ),
    ]
