# Generated by Django 3.2.7 on 2023-10-05 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0094_auto_20231004_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmissionrecords_model',
            name='facilityChoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 18, 51, 53, 408786)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 18, 51, 53, 408800)),
        ),
    ]
