# Generated by Django 3.2.7 on 2023-10-07 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0096_auto_20231005_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmissionrecords_model',
            name='formID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.forms'),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 13, 57, 54, 652208)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 13, 57, 54, 652226)),
        ),
    ]
