# Generated by Django 3.2.7 on 2023-10-19 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0098_auto_20231007_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 15, 36, 14, 208182)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 15, 36, 14, 208197)),
        ),
        migrations.CreateModel(
            name='form27_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=4)),
                ('date', models.DateField()),
                ('observer_5_1', models.CharField(blank=True, max_length=30, null=True)),
                ('date_5_1', models.DateField(blank=True, null=True)),
                ('time_5_1', models.TimeField(blank=True, null=True)),
                ('comments_5_1', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_5_1', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_5_1', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_5_1', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_5_1', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('observer_6_2', models.CharField(blank=True, max_length=30, null=True)),
                ('date_6_2', models.DateField(blank=True, null=True)),
                ('time_6_2', models.TimeField(blank=True, null=True)),
                ('comments_6_2', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_6_2', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_6_2', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_6_2', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_6_2', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('observer_7_3', models.CharField(blank=True, max_length=30, null=True)),
                ('date_7_3', models.DateField(blank=True, null=True)),
                ('time_7_3', models.TimeField(blank=True, null=True)),
                ('comments_7_3', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_7_3', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_7_3', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_7_3', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_7_3', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('observer_9_4', models.CharField(blank=True, max_length=30, null=True)),
                ('date_9_4', models.DateField(blank=True, null=True)),
                ('time_9_4', models.TimeField(blank=True, null=True)),
                ('comments_9_4', models.CharField(blank=True, max_length=30, null=True)),
                ('rear_gate_9_4', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_interior_9_4', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('box_exterior_9_4', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('exhaust_9_4', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True)),
                ('facilityChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model')),
            ],
        ),
    ]
