# Generated by Django 3.2.7 on 2023-10-19 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0099_auto_20231019_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='form26_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inspector', models.CharField(max_length=40)),
                ('skID', models.IntegerField()),
                ('type', models.CharField(choices=[('oil XL cart', 'PIG Spill Kit in Extra-Large Response Chest'), ('universal drum', 'PIG Spill Kit in Overpack Salvage Drum')], max_length=50)),
                ('counted_items', models.CharField(max_length=300)),
                ('missing_items', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 15, 56, 19, 380583)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 15, 56, 19, 380597)),
        ),
    ]
