# Generated by Django 3.2.7 on 2023-10-19 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0102_auto_20231019_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='form1_readings_model',
            fields=[
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EES_Forms.form1_model')),
                ('c1_no', models.CharField(max_length=2)),
                ('c2_no', models.CharField(max_length=2)),
                ('c3_no', models.CharField(max_length=2)),
                ('c4_no', models.CharField(max_length=2)),
                ('c5_no', models.CharField(max_length=2)),
                ('c1_start', models.TimeField(blank=True)),
                ('c2_start', models.TimeField(blank=True)),
                ('c3_start', models.TimeField(blank=True)),
                ('c4_start', models.TimeField(blank=True)),
                ('c5_start', models.TimeField(blank=True)),
                ('c1_stop', models.TimeField(blank=True)),
                ('c2_stop', models.TimeField(blank=True)),
                ('c3_stop', models.TimeField(blank=True)),
                ('c4_stop', models.TimeField(blank=True)),
                ('c5_stop', models.TimeField(blank=True)),
                ('c1_sec', models.FloatField(max_length=5)),
                ('c2_sec', models.FloatField(max_length=5)),
                ('c3_sec', models.FloatField(max_length=5)),
                ('c4_sec', models.FloatField(max_length=5)),
                ('c5_sec', models.FloatField(max_length=5)),
                ('c1_comments', models.CharField(max_length=150)),
                ('c2_comments', models.CharField(max_length=150)),
                ('c3_comments', models.CharField(max_length=150)),
                ('c4_comments', models.CharField(max_length=150)),
                ('c5_comments', models.CharField(max_length=150)),
                ('larry_car', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=30)),
                ('comments', models.CharField(max_length=600)),
                ('total_seconds', models.FloatField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 18, 6, 2, 73768)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 18, 6, 2, 73782)),
        ),
    ]
