# Generated by Django 3.2.7 on 2023-10-24 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0106_auto_20231024_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 16, 38, 42, 715985)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 16, 38, 42, 716000)),
        ),
    ]
