# Generated by Django 3.2.7 on 2023-10-26 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0107_auto_20231024_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_battery_profile_model',
            name='facilityChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EES_Forms.bat_info_model'),
        ),
        migrations.AlterField(
            model_name='event',
            name='personal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 19, 54, 35, 454646)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 19, 54, 35, 454665)),
        ),
    ]
