# Generated by Django 3.2.7 on 2023-10-27 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EES_Forms', '0109_auto_20231026_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_battery_profile_model',
            name='facility',
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='add_days',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 20, 17, 30, 131666)),
        ),
        migrations.AlterField(
            model_name='pt_admin1_model',
            name='days_left',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 20, 17, 30, 131680)),
        ),
    ]
